export const OtherLS = {
  type: "FeatureCollection",
  crs: { type: "name", properties: { name: "EPSG:6318" } },
  features: [
    {
      type: "Feature",
      id: 0,
      geometry: {
        type: "Point",
        coordinates: [-80.121816055808608, 25.986570558262397],
      },
      properties: {
        FID: 0,
        OBJECTID: 4,
        FACILITYID: "FL-05",
        STATIONID: "\u003cNull\u003e",
        BUILDYR: " ",
        STATIONTYP: " ",
        OWNEDBY: -8,
        LIFECYCLE: "Active",
        PROJECTNO: " ",
        WWSIZE: " ",
        LEVELRIM29: 0,
        LEVELINV29: 0,
        LEVELHIGH2: 0,
        LEVELLAG29: 0,
        LEVELLEAD2: 0,
        LEVELOFF29: 0,
        LEVELLOW29: 0,
        LEVELBASE2: 0,
        LEVELRIM88: 0,
        LEVELINV88: 0,
        LEVELHIGH8: 0,
        LEVELLAG88: 0,
        LEVELLEAD8: 0,
        LEVELOFF88: 0,
        LEVELLOW88: 0,
        LEVELBASE8: 0,
        MAINTBY: -5,
        GENERATOR: " ",
        FPLMETER: " ",
        FPLACCOUNT: " ",
        NUMBERPUMP: 0,
        LOCDESC: " ",
        GPSDATE: null,
        LATITUDE: "25.9865705582624",
        LONGITUDE: "-80.1218160558086",
        COMMENTS: " ",
        LASTUPDATE: 1404950400000,
        LASTEDITOR: "HOLLYWOOD\\mzaske",
        INSTALLYR: " ",
        COMPANY: "FL Dept. of Transportation",
        OWNERCONTA: " ",
        PHONEPAGER: " ",
        OFFICECELL: " ",
        OWNEREMAIL: " ",
        LIFTSTATIO: " ",
        STREETADDR: "Hallandale Bridge House",
        CITY: "Hallandale Beach",
        STATE: "FL",
        ZIPCODE: "33009",
        MAILINGADD: " ",
        MAILINGCIT: " ",
        MAILINGSTA: " ",
        MAILINGZIP: " ",
        SPILLPLANA: " ",
        MAINTENANC: " ",
        MAINTENA_1: " ",
        MAINTENA_2: " ",
        MAINTENA_3: " ",
        STATIONVOL: " ",
        TITLE: " ",
        LASTNAME: " ",
        FIRSTNAME: " ",
        POSITION: " ",
        LSTYPE: " ",
        GOESTO: " ",
        QTYRES: 0,
        QTYMFL: 0,
        QTYCOM: 0,
        HASBYPASS: " ",
        BYPASSVALV: 0,
        BYPASSFITT: " ",
        HURRICANEP: " ",
        FAX: " ",
        WWTP: "No",
        ParentID: " ",
      },
    },
    {
      type: "Feature",
      id: 1,
      geometry: {
        type: "Point",
        coordinates: [-80.215597947876148, 26.01188032628896],
      },
      properties: {
        FID: 1,
        OBJECTID: 9,
        FACILITYID: "SB-08",
        STATIONID: "SB-08",
        BUILDYR: " ",
        STATIONTYP: " ",
        OWNEDBY: -14,
        LIFECYCLE: "Active",
        PROJECTNO: " ",
        WWSIZE: " ",
        LEVELRIM29: 0,
        LEVELINV29: 0,
        LEVELHIGH2: 0,
        LEVELLAG29: 0,
        LEVELLEAD2: 0,
        LEVELOFF29: 0,
        LEVELLOW29: 0,
        LEVELBASE2: 0,
        LEVELRIM88: 0,
        LEVELINV88: 0,
        LEVELHIGH8: 0,
        LEVELLAG88: 0,
        LEVELLEAD8: 0,
        LEVELOFF88: 0,
        LEVELLOW88: 0,
        LEVELBASE8: 0,
        MAINTBY: -7,
        GENERATOR: " ",
        FPLMETER: " ",
        FPLACCOUNT: " ",
        NUMBERPUMP: 0,
        LOCDESC: " ",
        GPSDATE: null,
        LATITUDE: "26.011880326289",
        LONGITUDE: "-80.2155979478761",
        COMMENTS: " ",
        LASTUPDATE: 1404950400000,
        LASTEDITOR: "HOLLYWOOD\\mzaske",
        INSTALLYR: " ",
        COMPANY: "BC School Board",
        OWNERCONTA: " ",
        PHONEPAGER: " ",
        OFFICECELL: " ",
        OWNEREMAIL: " ",
        LIFTSTATIO: " ",
        STREETADDR: "6301 Hollywood Blvd",
        CITY: "Hollywood",
        STATE: "FL",
        ZIPCODE: "33027",
        MAILINGADD: " ",
        MAILINGCIT: " ",
        MAILINGSTA: " ",
        MAILINGZIP: " ",
        SPILLPLANA: " ",
        MAINTENANC: " ",
        MAINTENA_1: " ",
        MAINTENA_2: " ",
        MAINTENA_3: " ",
        STATIONVOL: " ",
        TITLE: " ",
        LASTNAME: " ",
        FIRSTNAME: " ",
        POSITION: " ",
        LSTYPE: " ",
        GOESTO: " ",
        QTYRES: 0,
        QTYMFL: 0,
        QTYCOM: 0,
        HASBYPASS: " ",
        BYPASSVALV: 0,
        BYPASSFITT: " ",
        HURRICANEP: " ",
        FAX: " ",
        WWTP: "No",
        ParentID: " ",
      },
    },
    {
      type: "Feature",
      id: 2,
      geometry: {
        type: "Point",
        coordinates: [-80.111744846955759, 26.05771522295807],
      },
      properties: {
        FID: 2,
        OBJECTID: 13,
        FACILITYID: "DB-01",
        STATIONID: " ",
        BUILDYR: " ",
        STATIONTYP: " ",
        OWNEDBY: -5,
        LIFECYCLE: "Active",
        PROJECTNO: " ",
        WWSIZE: " ",
        LEVELRIM29: 0,
        LEVELINV29: 0,
        LEVELHIGH2: 0,
        LEVELLAG29: 0,
        LEVELLEAD2: 0,
        LEVELOFF29: 0,
        LEVELLOW29: 0,
        LEVELBASE2: 0,
        LEVELRIM88: 0,
        LEVELINV88: 0,
        LEVELHIGH8: 0,
        LEVELLAG88: 0,
        LEVELLEAD8: 0,
        LEVELOFF88: 0,
        LEVELLOW88: 0,
        LEVELBASE8: 0,
        MAINTBY: -8,
        GENERATOR: " ",
        FPLMETER: " ",
        FPLACCOUNT: " ",
        NUMBERPUMP: 0,
        LOCDESC: " ",
        GPSDATE: null,
        LATITUDE: "26.0577152229581",
        LONGITUDE: "-80.1117448469558",
        COMMENTS: " ",
        LASTUPDATE: 1404950400000,
        LASTEDITOR: "HOLLYWOOD\\mzaske",
        INSTALLYR: " ",
        COMPANY: "City of Dania Beach",
        OWNERCONTA: " ",
        PHONEPAGER: " ",
        OFFICECELL: " ",
        OWNEREMAIL: " ",
        LIFTSTATIO: " ",
        STREETADDR: "45 N Beach Rd (Dania Beach Park)",
        CITY: "Dania Beach",
        STATE: "FL",
        ZIPCODE: "33004",
        MAILINGADD: " ",
        MAILINGCIT: " ",
        MAILINGSTA: " ",
        MAILINGZIP: " ",
        SPILLPLANA: " ",
        MAINTENANC: " ",
        MAINTENA_1: " ",
        MAINTENA_2: " ",
        MAINTENA_3: " ",
        STATIONVOL: " ",
        TITLE: " ",
        LASTNAME: " ",
        FIRSTNAME: " ",
        POSITION: " ",
        LSTYPE: " ",
        GOESTO: " ",
        QTYRES: 0,
        QTYMFL: 0,
        QTYCOM: 0,
        HASBYPASS: " ",
        BYPASSVALV: 0,
        BYPASSFITT: " ",
        HURRICANEP: " ",
        FAX: " ",
        WWTP: "No",
        ParentID: " ",
      },
    },
    {
      type: "Feature",
      id: 3,
      geometry: {
        type: "Point",
        coordinates: [-80.141561286751198, 26.008052900030293],
      },
      properties: {
        FID: 3,
        OBJECTID: 14,
        FACILITYID: "SB-06",
        STATIONID: " ",
        BUILDYR: " ",
        STATIONTYP: " ",
        OWNEDBY: -14,
        LIFECYCLE: "Active",
        PROJECTNO: " ",
        WWSIZE: " ",
        LEVELRIM29: 0,
        LEVELINV29: 0,
        LEVELHIGH2: 0,
        LEVELLAG29: 0,
        LEVELLEAD2: 0,
        LEVELOFF29: 0,
        LEVELLOW29: 0,
        LEVELBASE2: 0,
        LEVELRIM88: 0,
        LEVELINV88: 0,
        LEVELHIGH8: 0,
        LEVELLAG88: 0,
        LEVELLEAD8: 0,
        LEVELOFF88: 0,
        LEVELLOW88: 0,
        LEVELBASE8: 0,
        MAINTBY: -7,
        GENERATOR: " ",
        FPLMETER: " ",
        FPLACCOUNT: " ",
        NUMBERPUMP: 0,
        LOCDESC: " ",
        GPSDATE: null,
        LATITUDE: "26.0080529000303",
        LONGITUDE: "-80.1415612867512",
        COMMENTS: " ",
        LASTUPDATE: 1404950400000,
        LASTEDITOR: "HOLLYWOOD\\mzaske",
        INSTALLYR: " ",
        COMPANY: "BC School Board - Hollywood Central Elem",
        OWNERCONTA: "Set Aidie, P.E.",
        PHONEPAGER: " ",
        OFFICECELL: " ",
        OWNEREMAIL: " ",
        LIFTSTATIO: " ",
        STREETADDR: "1770 Monroe St",
        CITY: "Hollywood",
        STATE: "FL",
        ZIPCODE: "33020",
        MAILINGADD: " ",
        MAILINGCIT: " ",
        MAILINGSTA: " ",
        MAILINGZIP: " ",
        SPILLPLANA: " ",
        MAINTENANC: " ",
        MAINTENA_1: " ",
        MAINTENA_2: " ",
        MAINTENA_3: " ",
        STATIONVOL: " ",
        TITLE: " ",
        LASTNAME: " ",
        FIRSTNAME: " ",
        POSITION: " ",
        LSTYPE: " ",
        GOESTO: " ",
        QTYRES: 0,
        QTYMFL: 0,
        QTYCOM: 0,
        HASBYPASS: " ",
        BYPASSVALV: 0,
        BYPASSFITT: " ",
        HURRICANEP: " ",
        FAX: " ",
        WWTP: "No",
        ParentID: " ",
      },
    },
    {
      type: "Feature",
      id: 4,
      geometry: {
        type: "Point",
        coordinates: [-80.114434188509605, 26.034124175029188],
      },
      properties: {
        FID: 4,
        OBJECTID: 28,
        FACILITYID: "BC-01",
        STATIONID: " ",
        BUILDYR: " ",
        STATIONTYP: " ",
        OWNEDBY: -3,
        LIFECYCLE: "Active",
        PROJECTNO: " ",
        WWSIZE: " ",
        LEVELRIM29: 0,
        LEVELINV29: 0,
        LEVELHIGH2: 0,
        LEVELLAG29: 0,
        LEVELLEAD2: 0,
        LEVELOFF29: 0,
        LEVELLOW29: 0,
        LEVELBASE2: 0,
        LEVELRIM88: 0,
        LEVELINV88: 0,
        LEVELHIGH8: 0,
        LEVELLAG88: 0,
        LEVELLEAD8: 0,
        LEVELOFF88: 0,
        LEVELLOW88: 0,
        LEVELBASE8: 0,
        MAINTBY: -6,
        GENERATOR: " ",
        FPLMETER: " ",
        FPLACCOUNT: " ",
        NUMBERPUMP: 0,
        LOCDESC: " ",
        GPSDATE: null,
        LATITUDE: "26.0341241750292",
        LONGITUDE: "-80.1144341885096",
        COMMENTS: " ",
        LASTUPDATE: 1404950400000,
        LASTEDITOR: "HOLLYWOOD\\mzaske",
        INSTALLYR: " ",
        COMPANY: "BC Division of Parks and Recreation",
        OWNERCONTA: "Ms. Maureen O'Rourke",
        PHONEPAGER: "954-985-1960",
        OFFICECELL: " ",
        OWNEREMAIL: " ",
        LIFTSTATIO: "Ocean 3501",
        STREETADDR: "3501 N Ocean Dr",
        CITY: "Hollywood",
        STATE: "FL",
        ZIPCODE: "33021",
        MAILINGADD: "3300 N Park Rd",
        MAILINGCIT: "Hollywood",
        MAILINGSTA: "FL",
        MAILINGZIP: "33021",
        SPILLPLANA: " ",
        MAINTENANC: " ",
        MAINTENA_1: " ",
        MAINTENA_2: " ",
        MAINTENA_3: " ",
        STATIONVOL: " ",
        TITLE: " ",
        LASTNAME: " ",
        FIRSTNAME: " ",
        POSITION: " ",
        LSTYPE: " ",
        GOESTO: " ",
        QTYRES: 0,
        QTYMFL: 0,
        QTYCOM: 0,
        HASBYPASS: " ",
        BYPASSVALV: 0,
        BYPASSFITT: " ",
        HURRICANEP: " ",
        FAX: " ",
        WWTP: "No",
        ParentID: " ",
      },
    },
    {
      type: "Feature",
      id: 5,
      geometry: {
        type: "Point",
        coordinates: [-80.112245014848895, 26.089809866926284],
      },
      properties: {
        FID: 5,
        OBJECTID: 31,
        FACILITYID: "US-03",
        STATIONID: "E167-01",
        BUILDYR: " ",
        STATIONTYP: " ",
        OWNEDBY: -7,
        LIFECYCLE: "Active",
        PROJECTNO: " ",
        WWSIZE: " ",
        LEVELRIM29: 0,
        LEVELINV29: 0,
        LEVELHIGH2: 0,
        LEVELLAG29: 0,
        LEVELLEAD2: 0,
        LEVELOFF29: 0,
        LEVELLOW29: 0,
        LEVELBASE2: 0,
        LEVELRIM88: 0,
        LEVELINV88: 0,
        LEVELHIGH8: 0,
        LEVELLAG88: 0,
        LEVELLEAD8: 0,
        LEVELOFF88: 0,
        LEVELLOW88: 0,
        LEVELBASE8: 0,
        MAINTBY: -3,
        GENERATOR: " ",
        FPLMETER: " ",
        FPLACCOUNT: " ",
        NUMBERPUMP: 0,
        LOCDESC: "Coast Guard Station at Lloyd State Park",
        GPSDATE: 1133395200000,
        LATITUDE: "26.0898098669263",
        LONGITUDE: "-80.1122450148489",
        COMMENTS: " ",
        LASTUPDATE: 1602547200000,
        LASTEDITOR: "HOLLYWOOD\\JDIAZ-MARIN",
        INSTALLYR: " ",
        COMPANY: "U.S. Coast Guard",
        OWNERCONTA: "EM1, Joshua Herring",
        PHONEPAGER: "(954) 927-1611",
        OFFICECELL: "DC1 Jason Shepherd /305-395-1125",
        OWNEREMAIL: "joshua.c.herring@uscg.mil",
        LIFTSTATIO: "Ocean 7000",
        STREETADDR: "7000 N Ocean Dr",
        CITY: "Hollywood",
        STATE: "FL",
        ZIPCODE: "33004",
        MAILINGADD: "7000 N Ocean Dr",
        MAILINGCIT: "Dania Beach",
        MAILINGSTA: "FL",
        MAILINGZIP: "33004",
        SPILLPLANA: "1/6/2005",
        MAINTENANC: "South Florida Utilities, Inc.",
        MAINTENA_1: "Mark Carpenter",
        MAINTENA_2: "954-525-3751 (O), 954-732-5021(C)",
        MAINTENA_3: "sfluinc@yahoo.com",
        STATIONVOL: "200",
        TITLE: "EM1",
        LASTNAME: "Herring",
        FIRSTNAME: "Joshua",
        POSITION: "Engineering Officer",
        LSTYPE: "Residential",
        GOESTO: "SRWWTP",
        QTYRES: 0,
        QTYMFL: 0,
        QTYCOM: 1,
        HASBYPASS: "Yes",
        BYPASSVALV: 2,
        BYPASSFITT: "cAMLOCK",
        HURRICANEP: "Generator",
        FAX: "954-927-2270",
        WWTP: "No",
        ParentID: " ",
      },
    },
    {
      type: "Feature",
      id: 6,
      geometry: {
        type: "Point",
        coordinates: [-80.19651976943932, 26.014735552878108],
      },
      properties: {
        FID: 6,
        OBJECTID: 32,
        FACILITYID: "X-011",
        STATIONID: "SW109-01",
        BUILDYR: " ",
        STATIONTYP: "Other",
        OWNEDBY: -14,
        LIFECYCLE: "Active",
        PROJECTNO: " ",
        WWSIZE: " ",
        LEVELRIM29: 0,
        LEVELINV29: 0,
        LEVELHIGH2: 0,
        LEVELLAG29: 0,
        LEVELLEAD2: 0,
        LEVELOFF29: 0,
        LEVELLOW29: 0,
        LEVELBASE2: 0,
        LEVELRIM88: 0,
        LEVELINV88: 0,
        LEVELHIGH8: 0,
        LEVELLAG88: 0,
        LEVELLEAD8: 0,
        LEVELOFF88: 0,
        LEVELLOW88: 0,
        LEVELBASE8: 0,
        MAINTBY: -1,
        GENERATOR: " ",
        FPLMETER: "KJ38560",
        FPLACCOUNT: "Gg2b0m7e-0a241000",
        NUMBERPUMP: 2,
        LOCDESC: "SW of the Maintenance Bldg. between the S. parking lots",
        GPSDATE: 1134345600000,
        LATITUDE: "26.0147355528781",
        LONGITUDE: "-80.1965197694393",
        COMMENTS: " ",
        LASTUPDATE: 1602547200000,
        LASTEDITOR: "HOLLYWOOD\\JDIAZ-MARIN",
        INSTALLYR: " ",
        COMPANY: "Chaminade Madonna College Prepatory",
        OWNERCONTA: "Dennis Keller",
        PHONEPAGER: "954-989-5150 ext. 105",
        OFFICECELL: "954-459-1193 / 954-663-5688",
        OWNEREMAIL: "dkeller@cmlions.org / mcubillos@cmlions.org",
        LIFTSTATIO: "Chaminade 500",
        STREETADDR: "500 Chaminade Dr",
        CITY: "Hollywood",
        STATE: "FL",
        ZIPCODE: "33021",
        MAILINGADD: "500 East Chaminade Drive",
        MAILINGCIT: "Hollywood",
        MAILINGSTA: "FL",
        MAILINGZIP: "33021",
        SPILLPLANA: "12/6/2004",
        MAINTENANC: "Lift Stations R Us",
        MAINTENA_1: "Ms. Danette Suarez",
        MAINTENA_2: "1-305-324-2121, 1-305-345-4926 (C)",
        MAINTENA_3: "arianna@liftstationsrus.com",
        STATIONVOL: "230/460",
        TITLE: "Mr.",
        LASTNAME: "Keller",
        FIRSTNAME: "Dennis",
        POSITION: "Facilities Manager",
        LSTYPE: "Other",
        GOESTO: "SRWWTP",
        QTYRES: 0,
        QTYMFL: 0,
        QTYCOM: 1,
        HASBYPASS: "Yes",
        BYPASSVALV: 6,
        BYPASSFITT: " ",
        HURRICANEP: "Bypass",
        FAX: "954-983-4663",
        WWTP: " ",
        ParentID: " ",
      },
    },
    {
      type: "Feature",
      id: 7,
      geometry: {
        type: "Point",
        coordinates: [-80.20750342622533, 26.037826726442091],
      },
      properties: {
        FID: 7,
        OBJECTID: 33,
        FACILITYID: "ST-04",
        STATIONID: "NW171-01",
        BUILDYR: " ",
        STATIONTYP: " ",
        OWNEDBY: -15,
        LIFECYCLE: "Active",
        PROJECTNO: " ",
        WWSIZE: " ",
        LEVELRIM29: 0,
        LEVELINV29: 0,
        LEVELHIGH2: 0,
        LEVELLAG29: 0,
        LEVELLEAD2: 0,
        LEVELOFF29: 0,
        LEVELLOW29: 0,
        LEVELBASE2: 0,
        LEVELRIM88: 0,
        LEVELINV88: 0,
        LEVELHIGH8: 0,
        LEVELLAG88: 0,
        LEVELLEAD8: 0,
        LEVELOFF88: 0,
        LEVELLOW88: 0,
        LEVELBASE8: 0,
        MAINTBY: -4,
        GENERATOR: " ",
        FPLMETER: " ",
        FPLACCOUNT: " ",
        NUMBERPUMP: 0,
        LOCDESC: " ",
        GPSDATE: null,
        LATITUDE: "26.0378267264421",
        LONGITUDE: "-80.2075034262253",
        COMMENTS: " ",
        LASTUPDATE: 1404950400000,
        LASTEDITOR: "HOLLYWOOD\\mzaske",
        INSTALLYR: " ",
        COMPANY: "World Ford",
        OWNERCONTA: " ",
        PHONEPAGER: " ",
        OFFICECELL: " ",
        OWNEREMAIL: " ",
        LIFTSTATIO: " ",
        STREETADDR: "3101 N State Road 7",
        CITY: "Hollywood",
        STATE: "FL",
        ZIPCODE: "33024",
        MAILINGADD: " ",
        MAILINGCIT: " ",
        MAILINGSTA: " ",
        MAILINGZIP: " ",
        SPILLPLANA: " ",
        MAINTENANC: " ",
        MAINTENA_1: " ",
        MAINTENA_2: " ",
        MAINTENA_3: " ",
        STATIONVOL: " ",
        TITLE: " ",
        LASTNAME: " ",
        FIRSTNAME: " ",
        POSITION: " ",
        LSTYPE: " ",
        GOESTO: " ",
        QTYRES: 0,
        QTYMFL: 0,
        QTYCOM: 0,
        HASBYPASS: " ",
        BYPASSVALV: 0,
        BYPASSFITT: " ",
        HURRICANEP: " ",
        FAX: " ",
        WWTP: "No",
        ParentID: " ",
      },
    },
    {
      type: "Feature",
      id: 8,
      geometry: {
        type: "Point",
        coordinates: [-80.188165625042231, 26.003465165677998],
      },
      properties: {
        FID: 8,
        OBJECTID: 36,
        FACILITYID: "SB-04",
        STATIONID: "\u003cNull\u003e",
        BUILDYR: " ",
        STATIONTYP: " ",
        OWNEDBY: -14,
        LIFECYCLE: "Active",
        PROJECTNO: " ",
        WWSIZE: " ",
        LEVELRIM29: 0,
        LEVELINV29: 0,
        LEVELHIGH2: 0,
        LEVELLAG29: 0,
        LEVELLEAD2: 0,
        LEVELOFF29: 0,
        LEVELLOW29: 0,
        LEVELBASE2: 0,
        LEVELRIM88: 0,
        LEVELINV88: 0,
        LEVELHIGH8: 0,
        LEVELLAG88: 0,
        LEVELLEAD8: 0,
        LEVELOFF88: 0,
        LEVELLOW88: 0,
        LEVELBASE8: 0,
        MAINTBY: -7,
        GENERATOR: " ",
        FPLMETER: " ",
        FPLACCOUNT: " ",
        NUMBERPUMP: 0,
        LOCDESC: " ",
        GPSDATE: null,
        LATITUDE: "26.003465165678",
        LONGITUDE: "-80.1881656250422",
        COMMENTS: " ",
        LASTUPDATE: 1404950400000,
        LASTEDITOR: "HOLLYWOOD\\mzaske",
        INSTALLYR: " ",
        COMPANY: "BC School Board - Orangebrook Elem",
        OWNERCONTA: "Set Aidie, P.E.",
        PHONEPAGER: " ",
        OFFICECELL: " ",
        OWNEREMAIL: " ",
        LIFTSTATIO: " ",
        STREETADDR: "715 S 46th Ave",
        CITY: "Hallandale Beach",
        STATE: "FL",
        ZIPCODE: "33021",
        MAILINGADD: " ",
        MAILINGCIT: " ",
        MAILINGSTA: " ",
        MAILINGZIP: " ",
        SPILLPLANA: " ",
        MAINTENANC: " ",
        MAINTENA_1: " ",
        MAINTENA_2: " ",
        MAINTENA_3: " ",
        STATIONVOL: " ",
        TITLE: " ",
        LASTNAME: " ",
        FIRSTNAME: " ",
        POSITION: " ",
        LSTYPE: " ",
        GOESTO: " ",
        QTYRES: 0,
        QTYMFL: 0,
        QTYCOM: 0,
        HASBYPASS: " ",
        BYPASSVALV: 0,
        BYPASSFITT: " ",
        HURRICANEP: " ",
        FAX: " ",
        WWTP: "No",
        ParentID: " ",
      },
    },
    {
      type: "Feature",
      id: 9,
      geometry: {
        type: "Point",
        coordinates: [-80.199583288338445, 26.045525550445905],
      },
      properties: {
        FID: 9,
        OBJECTID: 37,
        FACILITYID: "SB-05",
        STATIONID: "\u003cNull\u003e",
        BUILDYR: " ",
        STATIONTYP: " ",
        OWNEDBY: -14,
        LIFECYCLE: "Active",
        PROJECTNO: " ",
        WWSIZE: " ",
        LEVELRIM29: 0,
        LEVELINV29: 0,
        LEVELHIGH2: 0,
        LEVELLAG29: 0,
        LEVELLEAD2: 0,
        LEVELOFF29: 0,
        LEVELLOW29: 0,
        LEVELBASE2: 0,
        LEVELRIM88: 0,
        LEVELINV88: 0,
        LEVELHIGH8: 0,
        LEVELLAG88: 0,
        LEVELLEAD8: 0,
        LEVELOFF88: 0,
        LEVELLOW88: 0,
        LEVELBASE8: 0,
        MAINTBY: -7,
        GENERATOR: " ",
        FPLMETER: " ",
        FPLACCOUNT: " ",
        NUMBERPUMP: 0,
        LOCDESC: " ",
        GPSDATE: 1133913600000,
        LATITUDE: "26.0455255504459",
        LONGITUDE: "-80.1995832883384",
        COMMENTS: " ",
        LASTUPDATE: 1404950400000,
        LASTEDITOR: "HOLLYWOOD\\mzaske",
        INSTALLYR: " ",
        COMPANY: "BC School Board - Stirling Elem",
        OWNERCONTA: "Set Aidie, P.E.",
        PHONEPAGER: " ",
        OFFICECELL: " ",
        OWNEREMAIL: " ",
        LIFTSTATIO: " ",
        STREETADDR: "5500 Stirling Rd",
        CITY: "Hallandale Beach",
        STATE: "FL",
        ZIPCODE: "33021",
        MAILINGADD: " ",
        MAILINGCIT: " ",
        MAILINGSTA: " ",
        MAILINGZIP: " ",
        SPILLPLANA: " ",
        MAINTENANC: " ",
        MAINTENA_1: " ",
        MAINTENA_2: " ",
        MAINTENA_3: " ",
        STATIONVOL: " ",
        TITLE: " ",
        LASTNAME: " ",
        FIRSTNAME: " ",
        POSITION: " ",
        LSTYPE: " ",
        GOESTO: " ",
        QTYRES: 0,
        QTYMFL: 0,
        QTYCOM: 0,
        HASBYPASS: " ",
        BYPASSVALV: 0,
        BYPASSFITT: " ",
        HURRICANEP: " ",
        FAX: " ",
        WWTP: "No",
        ParentID: " ",
      },
    },
    {
      type: "Feature",
      id: 10,
      geometry: {
        type: "Point",
        coordinates: [-80.234778472120936, 26.035966312835949],
      },
      properties: {
        FID: 10,
        OBJECTID: 38,
        FACILITYID: "DV-01",
        STATIONID: "\u003cNull\u003e",
        BUILDYR: " ",
        STATIONTYP: " ",
        OWNEDBY: -6,
        LIFECYCLE: "Active",
        PROJECTNO: " ",
        WWSIZE: " ",
        LEVELRIM29: 0,
        LEVELINV29: 0,
        LEVELHIGH2: 0,
        LEVELLAG29: 0,
        LEVELLEAD2: 0,
        LEVELOFF29: 0,
        LEVELLOW29: 0,
        LEVELBASE2: 0,
        LEVELRIM88: 0,
        LEVELINV88: 0,
        LEVELHIGH8: 0,
        LEVELLAG88: 0,
        LEVELLEAD8: 0,
        LEVELOFF88: 0,
        LEVELLOW88: 0,
        LEVELBASE8: 0,
        MAINTBY: -8,
        GENERATOR: "No",
        FPLMETER: " ",
        FPLACCOUNT: " ",
        NUMBERPUMP: 0,
        LOCDESC: " ",
        GPSDATE: null,
        LATITUDE: "26.0359663128359",
        LONGITUDE: "-80.2347784721209",
        COMMENTS: " ",
        LASTUPDATE: 1404950400000,
        LASTEDITOR: "HOLLYWOOD\\mzaske",
        INSTALLYR: " ",
        COMPANY: "Town of Davie (Valdevia)",
        OWNERCONTA: " ",
        PHONEPAGER: " ",
        OFFICECELL: " ",
        OWNEREMAIL: " ",
        LIFTSTATIO: " ",
        STREETADDR: "3001 N 73rd Avenue",
        CITY: "Hallandale Beach",
        STATE: "FL",
        ZIPCODE: "33009",
        MAILINGADD: " ",
        MAILINGCIT: " ",
        MAILINGSTA: " ",
        MAILINGZIP: " ",
        SPILLPLANA: " ",
        MAINTENANC: " ",
        MAINTENA_1: " ",
        MAINTENA_2: " ",
        MAINTENA_3: " ",
        STATIONVOL: " ",
        TITLE: " ",
        LASTNAME: " ",
        FIRSTNAME: " ",
        POSITION: " ",
        LSTYPE: " ",
        GOESTO: " ",
        QTYRES: 0,
        QTYMFL: 0,
        QTYCOM: 0,
        HASBYPASS: " ",
        BYPASSVALV: 0,
        BYPASSFITT: " ",
        HURRICANEP: " ",
        FAX: " ",
        WWTP: "No",
        ParentID: " ",
      },
    },
    {
      type: "Feature",
      id: 11,
      geometry: {
        type: "Point",
        coordinates: [-80.229484066980163, 26.033995791400123],
      },
      properties: {
        FID: 11,
        OBJECTID: 39,
        FACILITYID: "SB-02",
        STATIONID: "NW119-01",
        BUILDYR: " ",
        STATIONTYP: " ",
        OWNEDBY: -14,
        LIFECYCLE: "Active",
        PROJECTNO: " ",
        WWSIZE: " ",
        LEVELRIM29: 0,
        LEVELINV29: 0,
        LEVELHIGH2: 0,
        LEVELLAG29: 0,
        LEVELLEAD2: 0,
        LEVELOFF29: 0,
        LEVELLOW29: 0,
        LEVELBASE2: 0,
        LEVELRIM88: 0,
        LEVELINV88: 0,
        LEVELHIGH8: 0,
        LEVELLAG88: 0,
        LEVELLEAD8: 0,
        LEVELOFF88: 0,
        LEVELLOW88: 0,
        LEVELBASE8: 0,
        MAINTBY: -7,
        GENERATOR: " ",
        FPLMETER: " ",
        FPLACCOUNT: " ",
        NUMBERPUMP: 0,
        LOCDESC: " ",
        GPSDATE: 1133913600000,
        LATITUDE: "26.0339957914001",
        LONGITUDE: "-80.2294840669802",
        COMMENTS: " ",
        LASTUPDATE: 1404950400000,
        LASTEDITOR: "HOLLYWOOD\\mzaske",
        INSTALLYR: " ",
        COMPANY: "BC School Board - Driftwood Middle",
        OWNERCONTA: "Set Aidie, P.E.",
        PHONEPAGER: " ",
        OFFICECELL: " ",
        OWNEREMAIL: " ",
        LIFTSTATIO: " ",
        STREETADDR: "2751 NW 70 Ter",
        CITY: "Hollywood",
        STATE: "FL",
        ZIPCODE: "33024",
        MAILINGADD: " ",
        MAILINGCIT: " ",
        MAILINGSTA: " ",
        MAILINGZIP: " ",
        SPILLPLANA: " ",
        MAINTENANC: " ",
        MAINTENA_1: " ",
        MAINTENA_2: " ",
        MAINTENA_3: " ",
        STATIONVOL: " ",
        TITLE: " ",
        LASTNAME: " ",
        FIRSTNAME: " ",
        POSITION: " ",
        LSTYPE: " ",
        GOESTO: " ",
        QTYRES: 0,
        QTYMFL: 0,
        QTYCOM: 0,
        HASBYPASS: " ",
        BYPASSVALV: 0,
        BYPASSFITT: " ",
        HURRICANEP: " ",
        FAX: " ",
        WWTP: "No",
        ParentID: " ",
      },
    },
    {
      type: "Feature",
      id: 12,
      geometry: {
        type: "Point",
        coordinates: [-80.170982876418364, 25.984974574851357],
      },
      properties: {
        FID: 12,
        OBJECTID: 46,
        FACILITYID: "PP-01",
        STATIONID: "PP-01",
        BUILDYR: " ",
        STATIONTYP: " ",
        OWNEDBY: -12,
        LIFECYCLE: "Active",
        PROJECTNO: " ",
        WWSIZE: " ",
        LEVELRIM29: 0,
        LEVELINV29: 0,
        LEVELHIGH2: 0,
        LEVELLAG29: 0,
        LEVELLEAD2: 0,
        LEVELOFF29: 0,
        LEVELLOW29: 0,
        LEVELBASE2: 0,
        LEVELRIM88: 0,
        LEVELINV88: 0,
        LEVELHIGH8: 0,
        LEVELLAG88: 0,
        LEVELLEAD8: 0,
        LEVELOFF88: 0,
        LEVELLOW88: 0,
        LEVELBASE8: 0,
        MAINTBY: -8,
        GENERATOR: " ",
        FPLMETER: " ",
        FPLACCOUNT: " ",
        NUMBERPUMP: 0,
        LOCDESC: " ",
        GPSDATE: null,
        LATITUDE: "25.9849745748514",
        LONGITUDE: "-80.1709828764184",
        COMMENTS: " ",
        LASTUPDATE: 1404950400000,
        LASTEDITOR: "HOLLYWOOD\\mzaske",
        INSTALLYR: " ",
        COMPANY: "City of Pembroke Park",
        OWNERCONTA: " ",
        PHONEPAGER: " ",
        OFFICECELL: " ",
        OWNEREMAIL: " ",
        LIFTSTATIO: " ",
        STREETADDR: "3151 W Hallandale Beach Blvd",
        CITY: "Pembroke Park",
        STATE: "FL",
        ZIPCODE: "33009",
        MAILINGADD: " ",
        MAILINGCIT: " ",
        MAILINGSTA: " ",
        MAILINGZIP: " ",
        SPILLPLANA: " ",
        MAINTENANC: " ",
        MAINTENA_1: " ",
        MAINTENA_2: " ",
        MAINTENA_3: " ",
        STATIONVOL: " ",
        TITLE: " ",
        LASTNAME: " ",
        FIRSTNAME: " ",
        POSITION: " ",
        LSTYPE: " ",
        GOESTO: " ",
        QTYRES: 0,
        QTYMFL: 0,
        QTYCOM: 0,
        HASBYPASS: " ",
        BYPASSVALV: 0,
        BYPASSFITT: " ",
        HURRICANEP: " ",
        FAX: " ",
        WWTP: "No",
        ParentID: " ",
      },
    },
    {
      type: "Feature",
      id: 13,
      geometry: {
        type: "Point",
        coordinates: [-80.213021435419378, 26.008335227804686],
      },
      properties: {
        FID: 13,
        OBJECTID: 47,
        FACILITYID: "FL-06",
        STATIONID: " ",
        BUILDYR: " ",
        STATIONTYP: " ",
        OWNEDBY: -8,
        LIFECYCLE: "Active",
        PROJECTNO: " ",
        WWSIZE: " ",
        LEVELRIM29: 0,
        LEVELINV29: 0,
        LEVELHIGH2: 0,
        LEVELLAG29: 0,
        LEVELLEAD2: 0,
        LEVELOFF29: 0,
        LEVELLOW29: 0,
        LEVELBASE2: 0,
        LEVELRIM88: 0,
        LEVELINV88: 0,
        LEVELHIGH8: 0,
        LEVELLAG88: 0,
        LEVELLEAD8: 0,
        LEVELOFF88: 0,
        LEVELLOW88: 0,
        LEVELBASE8: 0,
        MAINTBY: -5,
        GENERATOR: " ",
        FPLMETER: " ",
        FPLACCOUNT: " ",
        NUMBERPUMP: 0,
        LOCDESC: " ",
        GPSDATE: null,
        LATITUDE: "26.0083352278047",
        LONGITUDE: "-80.2130214354194",
        COMMENTS: " ",
        LASTUPDATE: 1404950400000,
        LASTEDITOR: "HOLLYWOOD\\mzaske",
        INSTALLYR: " ",
        COMPANY: "FL Dept. of Transportation",
        OWNERCONTA: " ",
        PHONEPAGER: " ",
        OFFICECELL: " ",
        OWNEREMAIL: " ",
        LIFTSTATIO: " ",
        STREETADDR: "Turnpike Toll Plaza",
        CITY: " ",
        STATE: "FL",
        ZIPCODE: " ",
        MAILINGADD: " ",
        MAILINGCIT: " ",
        MAILINGSTA: " ",
        MAILINGZIP: " ",
        SPILLPLANA: " ",
        MAINTENANC: " ",
        MAINTENA_1: " ",
        MAINTENA_2: " ",
        MAINTENA_3: " ",
        STATIONVOL: " ",
        TITLE: " ",
        LASTNAME: " ",
        FIRSTNAME: " ",
        POSITION: " ",
        LSTYPE: " ",
        GOESTO: " ",
        QTYRES: 0,
        QTYMFL: 0,
        QTYCOM: 0,
        HASBYPASS: " ",
        BYPASSVALV: 0,
        BYPASSFITT: " ",
        HURRICANEP: " ",
        FAX: " ",
        WWTP: "No",
        ParentID: " ",
      },
    },
    {
      type: "Feature",
      id: 14,
      geometry: {
        type: "Point",
        coordinates: [-80.174296377217559, 25.995632478462507],
      },
      properties: {
        FID: 14,
        OBJECTID: 49,
        FACILITYID: "PP-19",
        STATIONID: "PP-19",
        BUILDYR: " ",
        STATIONTYP: "Submersible",
        OWNEDBY: -12,
        LIFECYCLE: "Active",
        PROJECTNO: " ",
        WWSIZE: " ",
        LEVELRIM29: 0,
        LEVELINV29: 0,
        LEVELHIGH2: 0,
        LEVELLAG29: 0,
        LEVELLEAD2: 0,
        LEVELOFF29: 0,
        LEVELLOW29: 0,
        LEVELBASE2: 0,
        LEVELRIM88: 0,
        LEVELINV88: 0,
        LEVELHIGH8: 0,
        LEVELLAG88: 0,
        LEVELLEAD8: 0,
        LEVELOFF88: 0,
        LEVELLOW88: 0,
        LEVELBASE8: 0,
        MAINTBY: -8,
        GENERATOR: " ",
        FPLMETER: " ",
        FPLACCOUNT: " ",
        NUMBERPUMP: 0,
        LOCDESC: " ",
        GPSDATE: null,
        LATITUDE: "25.9956324784625",
        LONGITUDE: "-80.1742963772176",
        COMMENTS: " ",
        LASTUPDATE: 1500508800000,
        LASTEDITOR: "HOLLYWOOD\\jdiaz-marin",
        INSTALLYR: " ",
        COMPANY: "City of Pembroke Park",
        OWNERCONTA: "Nick Tisi",
        PHONEPAGER: "(954) 931-7915",
        OFFICECELL: "(954) 629-9999",
        OWNEREMAIL: " ",
        LIFTSTATIO: " ",
        STREETADDR: "3350 Pembroke Rd",
        CITY: "Pembroke Park",
        STATE: "FL",
        ZIPCODE: "33021",
        MAILINGADD: " ",
        MAILINGCIT: " ",
        MAILINGSTA: " ",
        MAILINGZIP: " ",
        SPILLPLANA: " ",
        MAINTENANC: " ",
        MAINTENA_1: " ",
        MAINTENA_2: " ",
        MAINTENA_3: " ",
        STATIONVOL: " ",
        TITLE: " ",
        LASTNAME: "Tisi",
        FIRSTNAME: "Nick",
        POSITION: "Public Works Supervisor",
        LSTYPE: " ",
        GOESTO: " ",
        QTYRES: 0,
        QTYMFL: 0,
        QTYCOM: 0,
        HASBYPASS: " ",
        BYPASSVALV: 0,
        BYPASSFITT: " ",
        HURRICANEP: " ",
        FAX: " ",
        WWTP: "No",
        ParentID: " ",
      },
    },
    {
      type: "Feature",
      id: 15,
      geometry: {
        type: "Point",
        coordinates: [-80.114909710432826, 26.045278677678848],
      },
      properties: {
        FID: 15,
        OBJECTID: 103,
        FACILITYID: "BC-02",
        STATIONID: "E107-02",
        BUILDYR: "2007",
        STATIONTYP: " ",
        OWNEDBY: -3,
        LIFECYCLE: "Active",
        PROJECTNO: " ",
        WWSIZE: " ",
        LEVELRIM29: 0,
        LEVELINV29: 0,
        LEVELHIGH2: 0,
        LEVELLAG29: 0,
        LEVELLEAD2: 0,
        LEVELOFF29: 0,
        LEVELLOW29: 0,
        LEVELBASE2: 0,
        LEVELRIM88: 0,
        LEVELINV88: 0,
        LEVELHIGH8: 0,
        LEVELLAG88: 0,
        LEVELLEAD8: 0,
        LEVELOFF88: 0,
        LEVELLOW88: 0,
        LEVELBASE8: 0,
        MAINTBY: -6,
        GENERATOR: " ",
        FPLMETER: " ",
        FPLACCOUNT: " ",
        NUMBERPUMP: 1,
        LOCDESC: "Hawksbill  between Meade st. And Allen st.",
        GPSDATE: 1132617600000,
        LATITUDE: "26.0452786776788",
        LONGITUDE: "-80.1149097104328",
        COMMENTS: " ",
        LASTUPDATE: 1602547200000,
        LASTEDITOR: "HOLLYWOOD\\JDIAZ-MARIN",
        INSTALLYR: " ",
        COMPANY: "Broward County Parks and Recreation",
        OWNERCONTA: "Robert Sanguigni",
        PHONEPAGER: "Bob 954-410-4741 / Fred 954-296-7433",
        OFFICECELL: "954-357-8753",
        OWNEREMAIL: " ",
        LIFTSTATIO: "Ocean 3700",
        STREETADDR: "3700 N Ocean Dr",
        CITY: "Hollywood",
        STATE: "FL",
        ZIPCODE: "33021",
        MAILINGADD: "3900 SW 100th Ave",
        MAILINGCIT: "Davie",
        MAILINGSTA: "FL",
        MAILINGZIP: "33028",
        SPILLPLANA: "8/18/2004",
        MAINTENANC: "Broward Co. Staff- Brian Ortegus",
        MAINTENA_1: "Internal Maintenance",
        MAINTENA_2: "954-357-8753 (office)/Bob 954-410-4741 (cell)",
        MAINTENA_3: "fpulver@broward.org",
        STATIONVOL: "230",
        TITLE: "Mr.",
        LASTNAME: "Sanguigni",
        FIRSTNAME: "Robert",
        POSITION: "Maintenance Supervisor II",
        LSTYPE: "Other",
        GOESTO: "SRWWTP",
        QTYRES: 0,
        QTYMFL: 0,
        QTYCOM: 1,
        HASBYPASS: "Yes",
        BYPASSVALV: 2,
        BYPASSFITT: "Camlock",
        HURRICANEP: "Close Facility",
        FAX: "954-357-8741",
        WWTP: "No",
        ParentID: " ",
      },
    },
    {
      type: "Feature",
      id: 16,
      geometry: {
        type: "Point",
        coordinates: [-80.115209485799156, 26.039867946736308],
      },
      properties: {
        FID: 16,
        OBJECTID: 104,
        FACILITYID: "BC-03",
        STATIONID: "E107-01",
        BUILDYR: "2007",
        STATIONTYP: "Submersible",
        OWNEDBY: -3,
        LIFECYCLE: "Active",
        PROJECTNO: " ",
        WWSIZE: " ",
        LEVELRIM29: 0,
        LEVELINV29: 0,
        LEVELHIGH2: 0,
        LEVELLAG29: 0,
        LEVELLEAD2: 0,
        LEVELOFF29: 0,
        LEVELLOW29: 0,
        LEVELBASE2: 0,
        LEVELRIM88: 0,
        LEVELINV88: 0,
        LEVELHIGH8: 0,
        LEVELLAG88: 0,
        LEVELLEAD8: 0,
        LEVELOFF88: 0,
        LEVELLOW88: 0,
        LEVELBASE8: 0,
        MAINTBY: -6,
        GENERATOR: " ",
        FPLMETER: " ",
        FPLACCOUNT: " ",
        NUMBERPUMP: 1,
        LOCDESC: "leatherback",
        GPSDATE: 1132617600000,
        LATITUDE: "26.0398679467363",
        LONGITUDE: "-80.1152094857992",
        COMMENTS: " ",
        LASTUPDATE: 1602547200000,
        LASTEDITOR: "HOLLYWOOD\\JDIAZ-MARIN",
        INSTALLYR: " ",
        COMPANY: "Broward County Parks and Recreation",
        OWNERCONTA: "Robert Sanguigni",
        PHONEPAGER: "Bob 954-410-4741 / Fred 954-296-7433",
        OFFICECELL: "954-357-8753",
        OWNEREMAIL: "rsanguigno@broward.org",
        LIFTSTATIO: "Ocean 4300",
        STREETADDR: "5000 N Ocean Dr",
        CITY: "Hollywood",
        STATE: "FL",
        ZIPCODE: "33021",
        MAILINGADD: "3900 SW 100th Ave",
        MAILINGCIT: "Davie",
        MAILINGSTA: "FL",
        MAILINGZIP: "33028",
        SPILLPLANA: "8/18/2004",
        MAINTENANC: "Broward Co. Staff- Brian Ortegus",
        MAINTENA_1: "Internal Maintenance",
        MAINTENA_2: "954-357-8753 (office)/Bob 954-410-4741 (cell)",
        MAINTENA_3: "fpulver@broward.org",
        STATIONVOL: "230",
        TITLE: "Mr.",
        LASTNAME: "Sanguini",
        FIRSTNAME: "Robert",
        POSITION: "Maintenance Supervisor II",
        LSTYPE: "Other",
        GOESTO: "SRWWTP",
        QTYRES: 0,
        QTYMFL: 0,
        QTYCOM: 1,
        HASBYPASS: "Yes",
        BYPASSVALV: 2,
        BYPASSFITT: " ",
        HURRICANEP: "Close Facility",
        FAX: "954-357-8741",
        WWTP: "No",
        ParentID: " ",
      },
    },
    {
      type: "Feature",
      id: 17,
      geometry: {
        type: "Point",
        coordinates: [-80.116331857055016, 26.034971527491319],
      },
      properties: {
        FID: 17,
        OBJECTID: 105,
        FACILITYID: "BC-08",
        STATIONID: "E107-03",
        BUILDYR: " ",
        STATIONTYP: "Submersible",
        OWNEDBY: -3,
        LIFECYCLE: "Active",
        PROJECTNO: " ",
        WWSIZE: " ",
        LEVELRIM29: 0,
        LEVELINV29: 0,
        LEVELHIGH2: 0,
        LEVELLAG29: 0,
        LEVELLEAD2: 0,
        LEVELOFF29: 0,
        LEVELLOW29: 0,
        LEVELBASE2: 0,
        LEVELRIM88: 0,
        LEVELINV88: 0,
        LEVELHIGH8: 0,
        LEVELLAG88: 0,
        LEVELLEAD8: 0,
        LEVELOFF88: 0,
        LEVELLOW88: 0,
        LEVELBASE8: 0,
        MAINTBY: -6,
        GENERATOR: " ",
        FPLMETER: " ",
        FPLACCOUNT: " ",
        NUMBERPUMP: 2,
        LOCDESC: "Loggerhead ( corner of Sheridan)",
        GPSDATE: 1132617600000,
        LATITUDE: "26.0349715274913",
        LONGITUDE: "-80.116331857055",
        COMMENTS: " ",
        LASTUPDATE: 1602547200000,
        LASTEDITOR: "HOLLYWOOD\\JDIAZ-MARIN",
        INSTALLYR: " ",
        COMPANY: "Broward County Parks and Recreation",
        OWNERCONTA: " ",
        PHONEPAGER: "Bob 954-410-4741 / Fred 954-296-7433",
        OFFICECELL: "954-357-8753",
        OWNEREMAIL: " ",
        LIFTSTATIO: "Ocean 3501",
        STREETADDR: "3501 N Ocean Dr",
        CITY: "Hollywood",
        STATE: "FL",
        ZIPCODE: "33021",
        MAILINGADD: "3900 SW 100th Ave",
        MAILINGCIT: "Davie",
        MAILINGSTA: "FL",
        MAILINGZIP: "33028",
        SPILLPLANA: "8/18/2004",
        MAINTENANC: "Broward Co. Staff- Brian Ortegus",
        MAINTENA_1: "Internal Maintenance",
        MAINTENA_2: "954-357-8753 (office)/Bob 954-410-4741 (cell)",
        MAINTENA_3: "fpulver@broward.org",
        STATIONVOL: "230",
        TITLE: "Mr.",
        LASTNAME: "Sanguigni",
        FIRSTNAME: "Robert",
        POSITION: "Maintenance Supervisor II",
        LSTYPE: "Other",
        GOESTO: "SRWWTP",
        QTYRES: 0,
        QTYMFL: 0,
        QTYCOM: 1,
        HASBYPASS: "Yes",
        BYPASSVALV: 2,
        BYPASSFITT: "Camlock",
        HURRICANEP: "Close Facility",
        FAX: "954-357-8741",
        WWTP: "No",
        ParentID: " ",
      },
    },
    {
      type: "Feature",
      id: 18,
      geometry: {
        type: "Point",
        coordinates: [-80.109613672317266, 26.091829705650234],
      },
      properties: {
        FID: 18,
        OBJECTID: 118,
        FACILITYID: "US-01",
        STATIONID: "E143-01",
        BUILDYR: "2000",
        STATIONTYP: "Can",
        OWNEDBY: -7,
        LIFECYCLE: "Active",
        PROJECTNO: " ",
        WWSIZE: " ",
        LEVELRIM29: 0,
        LEVELINV29: 0,
        LEVELHIGH2: 0,
        LEVELLAG29: 0,
        LEVELLEAD2: 0,
        LEVELOFF29: 0,
        LEVELLOW29: 0,
        LEVELBASE2: 0,
        LEVELRIM88: 0,
        LEVELINV88: 0,
        LEVELHIGH8: 0,
        LEVELLAG88: 0,
        LEVELLEAD8: 0,
        LEVELOFF88: 0,
        LEVELLOW88: 0,
        LEVELBASE8: 0,
        MAINTBY: -1,
        GENERATOR: " ",
        FPLMETER: " ",
        FPLACCOUNT: " ",
        NUMBERPUMP: 2,
        LOCDESC:
          "Bldg. 50 South on the Naval Station at end of Lloyd State Park",
        GPSDATE: 1133395200000,
        LATITUDE: "26.0918297056502",
        LONGITUDE: "-80.1096136723173",
        COMMENTS: " ",
        LASTUPDATE: 1602547200000,
        LASTEDITOR: "HOLLYWOOD\\JDIAZ-MARIN",
        INSTALLYR: " ",
        COMPANY: "Naval Surface Warfare Center C/O The HP Group LLC",
        OWNERCONTA: "Russell Galvan",
        PHONEPAGER: "910-892-0726",
        OFFICECELL: "910-892-0726",
        OWNEREMAIL: "rgalvan@hpgorupsdv",
        LIFTSTATIO: "Ocean 8010",
        STREETADDR: "8010 N Ocean Road",
        CITY: "Dania Beach",
        STATE: "FL",
        ZIPCODE: "33004",
        MAILINGADD: "211 E Divine St",
        MAILINGCIT: "Dunn",
        MAILINGSTA: "NC",
        MAILINGZIP: "28334",
        SPILLPLANA: "10/5/2004",
        MAINTENANC: "Pumping Station Svc. Center",
        MAINTENA_1: "Art Ayala & J. C. Merchant",
        MAINTENA_2: " 1-561-758-1350 or 954-801-3649 1-954-969-1964 (cell)",
        MAINTENA_3: "art@pumpingstationservice.com",
        STATIONVOL: "230",
        TITLE: "Mr.",
        LASTNAME: "Galvan",
        FIRSTNAME: "Russell",
        POSITION: "Operations Manager",
        LSTYPE: "Commercial",
        GOESTO: "SRWWTP",
        QTYRES: 0,
        QTYMFL: 0,
        QTYCOM: 1,
        HASBYPASS: "Yes",
        BYPASSVALV: 2,
        BYPASSFITT: "camlock",
        HURRICANEP: "Close Facility",
        FAX: " ",
        WWTP: "No",
        ParentID: " ",
      },
    },
    {
      type: "Feature",
      id: 19,
      geometry: {
        type: "Point",
        coordinates: [-80.109989289188746, 26.091952553897816],
      },
      properties: {
        FID: 19,
        OBJECTID: 119,
        FACILITYID: "US-02",
        STATIONID: "E143-02",
        BUILDYR: "2000",
        STATIONTYP: "Can",
        OWNEDBY: -7,
        LIFECYCLE: "Active",
        PROJECTNO: " ",
        WWSIZE: " ",
        LEVELRIM29: 0,
        LEVELINV29: 0,
        LEVELHIGH2: 0,
        LEVELLAG29: 0,
        LEVELLEAD2: 0,
        LEVELOFF29: 0,
        LEVELLOW29: 0,
        LEVELBASE2: 0,
        LEVELRIM88: 0,
        LEVELINV88: 0,
        LEVELHIGH8: 0,
        LEVELLAG88: 0,
        LEVELLEAD8: 0,
        LEVELOFF88: 0,
        LEVELLOW88: 0,
        LEVELBASE8: 0,
        MAINTBY: -1,
        GENERATOR: " ",
        FPLMETER: " ",
        FPLACCOUNT: " ",
        NUMBERPUMP: 2,
        LOCDESC: "Warehouse at the Naval Station at end of Lloyd State Park",
        GPSDATE: 1133395200000,
        LATITUDE: "26.0919525538978",
        LONGITUDE: "-80.1099892891887",
        COMMENTS: " ",
        LASTUPDATE: 1602547200000,
        LASTEDITOR: "HOLLYWOOD\\JDIAZ-MARIN",
        INSTALLYR: " ",
        COMPANY: "Naval Surface Warfare Center / c/o The HP Group LLC",
        OWNERCONTA: "Mr. Russell Galvan",
        PHONEPAGER: "910-892-0726",
        OFFICECELL: "910-892-0726",
        OWNEREMAIL: "rgalvan@hpgroupsdv.com",
        LIFTSTATIO: "Ocean 8010",
        STREETADDR: "8010 N Ocean Road",
        CITY: "Dania Beach",
        STATE: "FL",
        ZIPCODE: "33004",
        MAILINGADD: "211 E Divine St",
        MAILINGCIT: "Dunn",
        MAILINGSTA: "NC",
        MAILINGZIP: "28334",
        SPILLPLANA: "10/5/2004",
        MAINTENANC: "Pumping Station Svc. Center",
        MAINTENA_1: "Art Ayala & J. C. Merchant",
        MAINTENA_2: " 1-561-758-1350 or 954-801-3649 1-954-969-1964 (cell)",
        MAINTENA_3: "art@pumpingstationservice.com",
        STATIONVOL: " ",
        TITLE: "Mr.",
        LASTNAME: "Galvan",
        FIRSTNAME: "Russell",
        POSITION: "Operations Manager",
        LSTYPE: "Commercial",
        GOESTO: "SRWWTP",
        QTYRES: 0,
        QTYMFL: 0,
        QTYCOM: 1,
        HASBYPASS: "Yes",
        BYPASSVALV: 2,
        BYPASSFITT: "Camlock",
        HURRICANEP: "Close Facility",
        FAX: " ",
        WWTP: "No",
        ParentID: " ",
      },
    },
    {
      type: "Feature",
      id: 20,
      geometry: {
        type: "Point",
        coordinates: [-80.112006629972456, 26.081082787103636],
      },
      properties: {
        FID: 20,
        OBJECTID: 120,
        FACILITYID: "FL-03",
        STATIONID: "E123-04",
        BUILDYR: " ",
        STATIONTYP: " ",
        OWNEDBY: -8,
        LIFECYCLE: "Active",
        PROJECTNO: " ",
        WWSIZE: " ",
        LEVELRIM29: 0,
        LEVELINV29: 0,
        LEVELHIGH2: 0,
        LEVELLAG29: 0,
        LEVELLEAD2: 0,
        LEVELOFF29: 0,
        LEVELLOW29: 0,
        LEVELBASE2: 0,
        LEVELRIM88: 0,
        LEVELINV88: 0,
        LEVELHIGH8: 0,
        LEVELLAG88: 0,
        LEVELLEAD8: 0,
        LEVELOFF88: 0,
        LEVELLOW88: 0,
        LEVELBASE8: 0,
        MAINTBY: -5,
        GENERATOR: " ",
        FPLMETER: " ",
        FPLACCOUNT: " ",
        NUMBERPUMP: 0,
        LOCDESC: " ",
        GPSDATE: 1133395200000,
        LATITUDE: "26.0810827871036",
        LONGITUDE: "-80.1120066299725",
        COMMENTS: " ",
        LASTUPDATE: 1404950400000,
        LASTEDITOR: "HOLLYWOOD\\mzaske",
        INSTALLYR: " ",
        COMPANY: "FL Dept. of Environmental Protection",
        OWNERCONTA: "Mr. Sidney J. Leve",
        PHONEPAGER: "954-924-3859",
        OFFICECELL: " ",
        OWNEREMAIL: " ",
        LIFTSTATIO: " ",
        STREETADDR: "6503 N Ocean Dr",
        CITY: "Hollywood",
        STATE: "FL",
        ZIPCODE: "33004",
        MAILINGADD: "6503 N Ocean Dr",
        MAILINGCIT: "Dania Beach",
        MAILINGSTA: "FL",
        MAILINGZIP: "33004",
        SPILLPLANA: " ",
        MAINTENANC: " ",
        MAINTENA_1: " ",
        MAINTENA_2: " ",
        MAINTENA_3: " ",
        STATIONVOL: " ",
        TITLE: " ",
        LASTNAME: " ",
        FIRSTNAME: " ",
        POSITION: " ",
        LSTYPE: " ",
        GOESTO: " ",
        QTYRES: 0,
        QTYMFL: 0,
        QTYCOM: 0,
        HASBYPASS: " ",
        BYPASSVALV: 0,
        BYPASSFITT: " ",
        HURRICANEP: " ",
        FAX: " ",
        WWTP: "No",
        ParentID: " ",
      },
    },
    {
      type: "Feature",
      id: 21,
      geometry: {
        type: "Point",
        coordinates: [-80.205123043637499, 26.035843528693963],
      },
      properties: {
        FID: 21,
        OBJECTID: 121,
        FACILITYID: "ST-05",
        STATIONID: "NW151-01",
        BUILDYR: " ",
        STATIONTYP: "Submersible",
        OWNEDBY: -15,
        LIFECYCLE: "Active",
        PROJECTNO: " ",
        WWSIZE: " ",
        LEVELRIM29: 0,
        LEVELINV29: 0,
        LEVELHIGH2: 0,
        LEVELLAG29: 0,
        LEVELLEAD2: 0,
        LEVELOFF29: 0,
        LEVELLOW29: 0,
        LEVELBASE2: 0,
        LEVELRIM88: 0,
        LEVELINV88: 0,
        LEVELHIGH8: 0,
        LEVELLAG88: 0,
        LEVELLEAD8: 0,
        LEVELOFF88: 0,
        LEVELLOW88: 0,
        LEVELBASE8: 0,
        MAINTBY: -4,
        GENERATOR: " ",
        FPLMETER: " ",
        FPLACCOUNT: " ",
        NUMBERPUMP: 2,
        LOCDESC: "N. side of Atlanta opposite 5926",
        GPSDATE: 1133740800000,
        LATITUDE: "26.035843528694",
        LONGITUDE: "-80.2051230436375",
        COMMENTS: " ",
        LASTUPDATE: 1602547200000,
        LASTEDITOR: "HOLLYWOOD\\JDIAZ-MARIN",
        INSTALLYR: " ",
        COMPANY: "R. S. Clay, Inc., d.b.a. R.V. Hideaway",
        OWNERCONTA: "Mr.  Roger Pinckney",
        PHONEPAGER: "954-966-3421",
        OFFICECELL: "954-966-3421",
        OWNEREMAIL: " ",
        LIFTSTATIO: "Atlanta 5925",
        STREETADDR: "2930 Randolph Clay Drive",
        CITY: "Hollywood",
        STATE: "FL",
        ZIPCODE: "33021",
        MAILINGADD: "2930 Randolph Clay Drive",
        MAILINGCIT: "Hollywood",
        MAILINGSTA: "FL",
        MAILINGZIP: "33021",
        SPILLPLANA: "9/10/2004",
        MAINTENANC: "South Florida Utilities, Inc.",
        MAINTENA_1: "Mark Carpenter",
        MAINTENA_2: "954-525-3751 (O), 954-732-5021(C)",
        MAINTENA_3: "sfluinc@yahoo.com",
        STATIONVOL: "230/1 phase",
        TITLE: "Mr.",
        LASTNAME: "Pinckney",
        FIRSTNAME: "Roger",
        POSITION: "President",
        LSTYPE: "Residential",
        GOESTO: "SRWWTP",
        QTYRES: 65,
        QTYMFL: 0,
        QTYCOM: 1,
        HASBYPASS: "No",
        BYPASSVALV: 0,
        BYPASSFITT: " ",
        HURRICANEP: "Generator",
        FAX: " ",
        WWTP: "No",
        ParentID: " ",
      },
    },
    {
      type: "Feature",
      id: 22,
      geometry: {
        type: "Point",
        coordinates: [-80.209931670922842, 26.043366123459574],
      },
      properties: {
        FID: 22,
        OBJECTID: 122,
        FACILITYID: "ST-01",
        STATIONID: "NW154-01",
        BUILDYR: " ",
        STATIONTYP: " ",
        OWNEDBY: -15,
        LIFECYCLE: "Active",
        PROJECTNO: " ",
        WWSIZE: " ",
        LEVELRIM29: 7.6700000700000004,
        LEVELINV29: 3,
        LEVELHIGH2: 1,
        LEVELLAG29: 0.5,
        LEVELLEAD2: 0,
        LEVELOFF29: -1.3300000400000001,
        LEVELLOW29: 0,
        LEVELBASE2: -2.5800000000000001,
        LEVELRIM88: 6.0900000700000003,
        LEVELINV88: 1.4199999999999999,
        LEVELHIGH8: -0.57999999999999996,
        LEVELLAG88: -1.0800000000000001,
        LEVELLEAD8: -1.5800000000000001,
        LEVELOFF88: -2.9100000399999999,
        LEVELLOW88: 0,
        LEVELBASE8: -4.1600000000000001,
        MAINTBY: -4,
        GENERATOR: " ",
        FPLMETER: " ",
        FPLACCOUNT: " ",
        NUMBERPUMP: 2,
        LOCDESC: " ",
        GPSDATE: 1133913600000,
        LATITUDE: "26.0433661234596",
        LONGITUDE: "-80.2099316709228",
        COMMENTS: " ",
        LASTUPDATE: 1404950400000,
        LASTEDITOR: "HOLLYWOOD\\mzaske",
        INSTALLYR: " ",
        COMPANY: "Seminole Indian Casino",
        OWNERCONTA: " ",
        PHONEPAGER: " ",
        OFFICECELL: " ",
        OWNEREMAIL: " ",
        LIFTSTATIO: " ",
        STREETADDR: "4150 N State Rd 7",
        CITY: "Hollywood",
        STATE: "FL",
        ZIPCODE: "33021",
        MAILINGADD: " ",
        MAILINGCIT: " ",
        MAILINGSTA: " ",
        MAILINGZIP: " ",
        SPILLPLANA: " ",
        MAINTENANC: " ",
        MAINTENA_1: " ",
        MAINTENA_2: " ",
        MAINTENA_3: " ",
        STATIONVOL: " ",
        TITLE: " ",
        LASTNAME: " ",
        FIRSTNAME: " ",
        POSITION: " ",
        LSTYPE: " ",
        GOESTO: " ",
        QTYRES: 0,
        QTYMFL: 0,
        QTYCOM: 0,
        HASBYPASS: " ",
        BYPASSVALV: 0,
        BYPASSFITT: " ",
        HURRICANEP: " ",
        FAX: " ",
        WWTP: "No",
        ParentID: " ",
      },
    },
    {
      type: "Feature",
      id: 23,
      geometry: {
        type: "Point",
        coordinates: [-80.205280750098339, 26.038928492981594],
      },
      properties: {
        FID: 23,
        OBJECTID: 123,
        FACILITYID: "ST-02",
        STATIONID: "NW155-01",
        BUILDYR: " ",
        STATIONTYP: " ",
        OWNEDBY: -15,
        LIFECYCLE: "Active",
        PROJECTNO: " ",
        WWSIZE: " ",
        LEVELRIM29: 0,
        LEVELINV29: 0,
        LEVELHIGH2: 0,
        LEVELLAG29: 0,
        LEVELLEAD2: 0,
        LEVELOFF29: 0,
        LEVELLOW29: 0,
        LEVELBASE2: 0,
        LEVELRIM88: 0,
        LEVELINV88: 0,
        LEVELHIGH8: 0,
        LEVELLAG88: 0,
        LEVELLEAD8: 0,
        LEVELOFF88: 0,
        LEVELLOW88: 0,
        LEVELBASE8: 0,
        MAINTBY: -4,
        GENERATOR: " ",
        FPLMETER: " ",
        FPLACCOUNT: " ",
        NUMBERPUMP: 0,
        LOCDESC: " ",
        GPSDATE: 1133913600000,
        LATITUDE: "26.0389284929816",
        LONGITUDE: "-80.2052807500983",
        COMMENTS: " ",
        LASTUPDATE: 1404950400000,
        LASTEDITOR: "HOLLYWOOD\\mzaske",
        INSTALLYR: " ",
        COMPANY: "Seminole Park",
        OWNERCONTA: " ",
        PHONEPAGER: " ",
        OFFICECELL: " ",
        OWNEREMAIL: " ",
        LIFTSTATIO: " ",
        STREETADDR: "3301 N State Rd 7",
        CITY: "Hollywood",
        STATE: "FL",
        ZIPCODE: "33021-2150",
        MAILINGADD: " ",
        MAILINGCIT: " ",
        MAILINGSTA: " ",
        MAILINGZIP: " ",
        SPILLPLANA: " ",
        MAINTENANC: " ",
        MAINTENA_1: " ",
        MAINTENA_2: " ",
        MAINTENA_3: " ",
        STATIONVOL: " ",
        TITLE: " ",
        LASTNAME: " ",
        FIRSTNAME: " ",
        POSITION: " ",
        LSTYPE: " ",
        GOESTO: " ",
        QTYRES: 0,
        QTYMFL: 0,
        QTYCOM: 0,
        HASBYPASS: " ",
        BYPASSVALV: 0,
        BYPASSFITT: " ",
        HURRICANEP: " ",
        FAX: " ",
        WWTP: "No",
        ParentID: " ",
      },
    },
    {
      type: "Feature",
      id: 24,
      geometry: {
        type: "Point",
        coordinates: [-80.229830120020296, 26.030926972789661],
      },
      properties: {
        FID: 24,
        OBJECTID: 124,
        FACILITYID: "SB-03",
        STATIONID: "\u003cNull\u003e",
        BUILDYR: " ",
        STATIONTYP: " ",
        OWNEDBY: -14,
        LIFECYCLE: "Active",
        PROJECTNO: " ",
        WWSIZE: " ",
        LEVELRIM29: 0,
        LEVELINV29: 0,
        LEVELHIGH2: 0,
        LEVELLAG29: 0,
        LEVELLEAD2: 0,
        LEVELOFF29: 0,
        LEVELLOW29: 0,
        LEVELBASE2: 0,
        LEVELRIM88: 0,
        LEVELINV88: 0,
        LEVELHIGH8: 0,
        LEVELLAG88: 0,
        LEVELLEAD8: 0,
        LEVELOFF88: 0,
        LEVELLOW88: 0,
        LEVELBASE8: 0,
        MAINTBY: -7,
        GENERATOR: " ",
        FPLMETER: " ",
        FPLACCOUNT: " ",
        NUMBERPUMP: 0,
        LOCDESC: " ",
        GPSDATE: 1133913600000,
        LATITUDE: "26.0309269727897",
        LONGITUDE: "-80.2298301200203",
        COMMENTS: " ",
        LASTUPDATE: 1404950400000,
        LASTEDITOR: "HOLLYWOOD\\mzaske",
        INSTALLYR: " ",
        COMPANY: "BC School Board - Sheridan Park Elem",
        OWNERCONTA: "Set Aidie, P.E.",
        PHONEPAGER: " ",
        OFFICECELL: " ",
        OWNEREMAIL: " ",
        LIFTSTATIO: " ",
        STREETADDR: "2310 NW 70th Ter",
        CITY: "Hallandale Beach",
        STATE: "FL",
        ZIPCODE: "33024",
        MAILINGADD: " ",
        MAILINGCIT: " ",
        MAILINGSTA: " ",
        MAILINGZIP: " ",
        SPILLPLANA: " ",
        MAINTENANC: " ",
        MAINTENA_1: " ",
        MAINTENA_2: " ",
        MAINTENA_3: " ",
        STATIONVOL: " ",
        TITLE: " ",
        LASTNAME: " ",
        FIRSTNAME: " ",
        POSITION: " ",
        LSTYPE: " ",
        GOESTO: " ",
        QTYRES: 0,
        QTYMFL: 0,
        QTYCOM: 0,
        HASBYPASS: " ",
        BYPASSVALV: 0,
        BYPASSFITT: " ",
        HURRICANEP: " ",
        FAX: " ",
        WWTP: "No",
        ParentID: " ",
      },
    },
    {
      type: "Feature",
      id: 25,
      geometry: {
        type: "Point",
        coordinates: [-80.175231531627333, 26.037713212388724],
      },
      properties: {
        FID: 25,
        OBJECTID: 153,
        FACILITYID: "BC-04",
        STATIONID: "NW107-06",
        BUILDYR: "2018",
        STATIONTYP: "Other",
        OWNEDBY: -3,
        LIFECYCLE: "Active",
        PROJECTNO: " ",
        WWSIZE: " ",
        LEVELRIM29: 0,
        LEVELINV29: 0,
        LEVELHIGH2: 0,
        LEVELLAG29: 0,
        LEVELLEAD2: 0,
        LEVELOFF29: 0,
        LEVELLOW29: 0,
        LEVELBASE2: 0,
        LEVELRIM88: 0,
        LEVELINV88: 0,
        LEVELHIGH8: 0,
        LEVELLAG88: 0,
        LEVELLEAD8: 0,
        LEVELOFF88: 0,
        LEVELLOW88: 0,
        LEVELBASE8: 0,
        MAINTBY: -6,
        GENERATOR: " ",
        FPLMETER: " ",
        FPLACCOUNT: " ",
        NUMBERPUMP: 2,
        LOCDESC: "TY Park West",
        GPSDATE: 1133740800000,
        LATITUDE: "26.0377132123887",
        LONGITUDE: "-80.1752315316273",
        COMMENTS: "Station was rebuilt on 2020",
        LASTUPDATE: 1602547200000,
        LASTEDITOR: "HOLLYWOOD\\JDIAZ-MARIN",
        INSTALLYR: " ",
        COMPANY: "Broward County Parks and Recreation",
        OWNERCONTA: "Mr. Bob Sanguigni",
        PHONEPAGER: "Bob 954-410-4741 / Fred 954-296-7433",
        OFFICECELL: "954-357-8753",
        OWNEREMAIL: "Rsanguigni@broward.org",
        LIFTSTATIO: "Park 3300",
        STREETADDR: "3300 N Park Rd",
        CITY: "Hollywood",
        STATE: "FL",
        ZIPCODE: "33021",
        MAILINGADD: "3900 SW 100th Ave",
        MAILINGCIT: "Davie",
        MAILINGSTA: "FL",
        MAILINGZIP: "33028",
        SPILLPLANA: "8/18/2004",
        MAINTENANC: "Broward Co. Staff- Brian Ortegus",
        MAINTENA_1: "Internal Maintenance",
        MAINTENA_2: "954-357-8753 (office)/Bob 954-410-4741 (cell)",
        MAINTENA_3: "fpulver@broward.org",
        STATIONVOL: "240/3phase",
        TITLE: "Mr.",
        LASTNAME: "Sanguigni",
        FIRSTNAME: "Robert",
        POSITION: "Maintenance Supervisor II",
        LSTYPE: "Other",
        GOESTO: "SRWWTP",
        QTYRES: 0,
        QTYMFL: 0,
        QTYCOM: 1,
        HASBYPASS: "Yes",
        BYPASSVALV: 6,
        BYPASSFITT: "Pump out",
        HURRICANEP: "Close Facility",
        FAX: "954-357-8741",
        WWTP: "No",
        ParentID: " ",
      },
    },
    {
      type: "Feature",
      id: 26,
      geometry: {
        type: "Point",
        coordinates: [-80.15319959706386, 26.044119661085301],
      },
      properties: {
        FID: 26,
        OBJECTID: 175,
        FACILITYID: "X-109",
        STATIONID: " ",
        BUILDYR: " ",
        STATIONTYP: " ",
        OWNEDBY: -14,
        LIFECYCLE: "Active",
        PROJECTNO: " ",
        WWSIZE: " ",
        LEVELRIM29: 0,
        LEVELINV29: 0,
        LEVELHIGH2: 0,
        LEVELLAG29: 0,
        LEVELLEAD2: 0,
        LEVELOFF29: 0,
        LEVELLOW29: 0,
        LEVELBASE2: 0,
        LEVELRIM88: 0,
        LEVELINV88: 0,
        LEVELHIGH8: 0,
        LEVELLAG88: 0,
        LEVELLEAD8: 0,
        LEVELOFF88: 0,
        LEVELLOW88: 0,
        LEVELBASE8: 0,
        MAINTBY: -7,
        GENERATOR: " ",
        FPLMETER: " ",
        FPLACCOUNT: " ",
        NUMBERPUMP: 0,
        LOCDESC: " ",
        GPSDATE: 1132704000000,
        LATITUDE: "26.0441196610853",
        LONGITUDE: "-80.1531995970639",
        COMMENTS: " ",
        LASTUPDATE: 1404950400000,
        LASTEDITOR: "HOLLYWOOD\\mzaske",
        INSTALLYR: " ",
        COMPANY: "BC School Board",
        OWNERCONTA: " ",
        PHONEPAGER: " ",
        OFFICECELL: " ",
        OWNEREMAIL: " ",
        LIFTSTATIO: " ",
        STREETADDR: "3500 N 22 Ave",
        CITY: "Hollywood",
        STATE: "FL",
        ZIPCODE: "33020",
        MAILINGADD: " ",
        MAILINGCIT: " ",
        MAILINGSTA: " ",
        MAILINGZIP: " ",
        SPILLPLANA: " ",
        MAINTENANC: " ",
        MAINTENA_1: " ",
        MAINTENA_2: " ",
        MAINTENA_3: " ",
        STATIONVOL: " ",
        TITLE: " ",
        LASTNAME: " ",
        FIRSTNAME: " ",
        POSITION: " ",
        LSTYPE: " ",
        GOESTO: " ",
        QTYRES: 0,
        QTYMFL: 0,
        QTYCOM: 0,
        HASBYPASS: " ",
        BYPASSVALV: 0,
        BYPASSFITT: " ",
        HURRICANEP: " ",
        FAX: " ",
        WWTP: "No",
        ParentID: " ",
      },
    },
    {
      type: "Feature",
      id: 27,
      geometry: {
        type: "Point",
        coordinates: [-80.211495994230248, 26.037563894697943],
      },
      properties: {
        FID: 27,
        OBJECTID: 179,
        FACILITYID: "ST-03",
        STATIONID: "\u003cNull\u003e",
        BUILDYR: " ",
        STATIONTYP: " ",
        OWNEDBY: -15,
        LIFECYCLE: "Active",
        PROJECTNO: " ",
        WWSIZE: " ",
        LEVELRIM29: 7.6500000000000004,
        LEVELINV29: 0.14000000000000001,
        LEVELHIGH2: -1.1000000000000001,
        LEVELLAG29: -1.6000000000000001,
        LEVELLEAD2: -2.1000000000000001,
        LEVELOFF29: -5.0999999999999996,
        LEVELLOW29: 0,
        LEVELBASE2: -6.0999999999999996,
        LEVELRIM88: 6.0700000000000003,
        LEVELINV88: -1.4399999999999999,
        LEVELHIGH8: -2.6800000000000002,
        LEVELLAG88: -3.1800000000000002,
        LEVELLEAD8: -3.6800000000000002,
        LEVELOFF88: -6.6799999999999997,
        LEVELLOW88: 0,
        LEVELBASE8: -7.6799999999999997,
        MAINTBY: -4,
        GENERATOR: " ",
        FPLMETER: " ",
        FPLACCOUNT: " ",
        NUMBERPUMP: 0,
        LOCDESC: " ",
        GPSDATE: null,
        LATITUDE: "26.0375638946979",
        LONGITUDE: "-80.2114959942302",
        COMMENTS: " ",
        LASTUPDATE: 1404950400000,
        LASTEDITOR: "HOLLYWOOD\\mzaske",
        INSTALLYR: " ",
        COMPANY: " ",
        OWNERCONTA: " ",
        PHONEPAGER: " ",
        OFFICECELL: " ",
        OWNEREMAIL: " ",
        LIFTSTATIO: " ",
        STREETADDR: "Hollywood Seminole Estates, 3300 N State Rd 7",
        CITY: "Hollywood",
        STATE: "FL",
        ZIPCODE: "33021",
        MAILINGADD: " ",
        MAILINGCIT: " ",
        MAILINGSTA: " ",
        MAILINGZIP: " ",
        SPILLPLANA: " ",
        MAINTENANC: " ",
        MAINTENA_1: " ",
        MAINTENA_2: " ",
        MAINTENA_3: " ",
        STATIONVOL: " ",
        TITLE: " ",
        LASTNAME: " ",
        FIRSTNAME: " ",
        POSITION: " ",
        LSTYPE: " ",
        GOESTO: " ",
        QTYRES: 0,
        QTYMFL: 0,
        QTYCOM: 0,
        HASBYPASS: " ",
        BYPASSVALV: 0,
        BYPASSFITT: " ",
        HURRICANEP: " ",
        FAX: " ",
        WWTP: "No",
        ParentID: " ",
      },
    },
    {
      type: "Feature",
      id: 28,
      geometry: {
        type: "Point",
        coordinates: [-80.155267948042152, 26.046259443910134],
      },
      properties: {
        FID: 28,
        OBJECTID: 202,
        FACILITYID: "X-111",
        STATIONID: " ",
        BUILDYR: "2003",
        STATIONTYP: " ",
        OWNEDBY: -14,
        LIFECYCLE: "Active",
        PROJECTNO: " ",
        WWSIZE: " ",
        LEVELRIM29: 7.9900000000000002,
        LEVELINV29: 0,
        LEVELHIGH2: 0,
        LEVELLAG29: 0,
        LEVELLEAD2: 0,
        LEVELOFF29: 0,
        LEVELLOW29: 0,
        LEVELBASE2: 0,
        LEVELRIM88: 6.4100000000000001,
        LEVELINV88: 0,
        LEVELHIGH8: 0,
        LEVELLAG88: 0,
        LEVELLEAD8: 0,
        LEVELOFF88: 0,
        LEVELLOW88: 0,
        LEVELBASE8: 0,
        MAINTBY: -7,
        GENERATOR: " ",
        FPLMETER: " ",
        FPLACCOUNT: " ",
        NUMBERPUMP: 0,
        LOCDESC: " ",
        GPSDATE: null,
        LATITUDE: "26.0462594439101",
        LONGITUDE: "-80.1552679480422",
        COMMENTS: " ",
        LASTUPDATE: 1404950400000,
        LASTEDITOR: "HOLLYWOOD\\mzaske",
        INSTALLYR: " ",
        COMPANY: "BC School Board",
        OWNERCONTA: " ",
        PHONEPAGER: " ",
        OFFICECELL: " ",
        OWNEREMAIL: " ",
        LIFTSTATIO: " ",
        STREETADDR: "3500 N 22 Ave",
        CITY: "Hollywood",
        STATE: "FL",
        ZIPCODE: "33020",
        MAILINGADD: " ",
        MAILINGCIT: " ",
        MAILINGSTA: " ",
        MAILINGZIP: " ",
        SPILLPLANA: " ",
        MAINTENANC: " ",
        MAINTENA_1: " ",
        MAINTENA_2: " ",
        MAINTENA_3: " ",
        STATIONVOL: " ",
        TITLE: " ",
        LASTNAME: " ",
        FIRSTNAME: " ",
        POSITION: " ",
        LSTYPE: " ",
        GOESTO: " ",
        QTYRES: 0,
        QTYMFL: 0,
        QTYCOM: 0,
        HASBYPASS: " ",
        BYPASSVALV: 0,
        BYPASSFITT: " ",
        HURRICANEP: " ",
        FAX: " ",
        WWTP: "No",
        ParentID: " ",
      },
    },
    {
      type: "Feature",
      id: 29,
      geometry: {
        type: "Point",
        coordinates: [-80.155729100556812, 26.044696913129641],
      },
      properties: {
        FID: 29,
        OBJECTID: 203,
        FACILITYID: "SB-07",
        STATIONID: "\u003cNull\u003e",
        BUILDYR: " ",
        STATIONTYP: " ",
        OWNEDBY: -14,
        LIFECYCLE: "Active",
        PROJECTNO: " ",
        WWSIZE: " ",
        LEVELRIM29: 0,
        LEVELINV29: 0,
        LEVELHIGH2: 0,
        LEVELLAG29: 0,
        LEVELLEAD2: 0,
        LEVELOFF29: 0,
        LEVELLOW29: 0,
        LEVELBASE2: 0,
        LEVELRIM88: 0,
        LEVELINV88: 0,
        LEVELHIGH8: 0,
        LEVELLAG88: 0,
        LEVELLEAD8: 0,
        LEVELOFF88: 0,
        LEVELLOW88: 0,
        LEVELBASE8: 0,
        MAINTBY: -7,
        GENERATOR: " ",
        FPLMETER: " ",
        FPLACCOUNT: " ",
        NUMBERPUMP: 0,
        LOCDESC: " ",
        GPSDATE: 1132704000000,
        LATITUDE: "26.0446999487653",
        LONGITUDE: "-80.1557581593656",
        COMMENTS: " ",
        LASTUPDATE: 1404950400000,
        LASTEDITOR: "HOLLYWOOD\\mzaske",
        INSTALLYR: " ",
        COMPANY: "BC School Board - Attucks Middle",
        OWNERCONTA: "Set Aidie, P.E.",
        PHONEPAGER: " ",
        OFFICECELL: " ",
        OWNEREMAIL: " ",
        LIFTSTATIO: " ",
        STREETADDR: "3500 N 22nd Ave",
        CITY: "Hollywood",
        STATE: "FL",
        ZIPCODE: "33020",
        MAILINGADD: " ",
        MAILINGCIT: " ",
        MAILINGSTA: " ",
        MAILINGZIP: " ",
        SPILLPLANA: " ",
        MAINTENANC: " ",
        MAINTENA_1: " ",
        MAINTENA_2: " ",
        MAINTENA_3: " ",
        STATIONVOL: " ",
        TITLE: " ",
        LASTNAME: " ",
        FIRSTNAME: " ",
        POSITION: " ",
        LSTYPE: " ",
        GOESTO: " ",
        QTYRES: 0,
        QTYMFL: 0,
        QTYCOM: 0,
        HASBYPASS: " ",
        BYPASSVALV: 0,
        BYPASSFITT: " ",
        HURRICANEP: " ",
        FAX: " ",
        WWTP: "No",
        ParentID: " ",
      },
    },
    {
      type: "Feature",
      id: 30,
      geometry: {
        type: "Point",
        coordinates: [-80.160172213572991, 26.001650529478162],
      },
      properties: {
        FID: 30,
        OBJECTID: 210,
        FACILITYID: "X-114",
        STATIONID: " ",
        BUILDYR: " ",
        STATIONTYP: "Submersible",
        OWNEDBY: -14,
        LIFECYCLE: "Active",
        PROJECTNO: "05-2099",
        WWSIZE: " ",
        LEVELRIM29: 14.300000000000001,
        LEVELINV29: 0,
        LEVELHIGH2: 0,
        LEVELLAG29: 0,
        LEVELLEAD2: 0,
        LEVELOFF29: 0,
        LEVELLOW29: 0,
        LEVELBASE2: 0,
        LEVELRIM88: 12.720000000000001,
        LEVELINV88: 0,
        LEVELHIGH8: 0,
        LEVELLAG88: 0,
        LEVELLEAD8: 0,
        LEVELOFF88: 0,
        LEVELLOW88: 0,
        LEVELBASE8: 0,
        MAINTBY: -7,
        GENERATOR: " ",
        FPLMETER: " ",
        FPLACCOUNT: " ",
        NUMBERPUMP: 2,
        LOCDESC: " ",
        GPSDATE: null,
        LATITUDE: "26.0016505294782",
        LONGITUDE: "-80.160172213573",
        COMMENTS: " ",
        LASTUPDATE: 1507075200000,
        LASTEDITOR: "HOLLYWOOD\\mzaske",
        INSTALLYR: "2007",
        COMPANY: "BC School Board - Colbert",
        OWNERCONTA: " ",
        PHONEPAGER: " ",
        OFFICECELL: " ",
        OWNEREMAIL: " ",
        LIFTSTATIO: " ",
        STREETADDR: "2701 Plunkett St",
        CITY: "Hollywood",
        STATE: "FL",
        ZIPCODE: "33020",
        MAILINGADD: " ",
        MAILINGCIT: " ",
        MAILINGSTA: " ",
        MAILINGZIP: " ",
        SPILLPLANA: " ",
        MAINTENANC: " ",
        MAINTENA_1: " ",
        MAINTENA_2: " ",
        MAINTENA_3: " ",
        STATIONVOL: " ",
        TITLE: " ",
        LASTNAME: " ",
        FIRSTNAME: " ",
        POSITION: " ",
        LSTYPE: " ",
        GOESTO: "SRWWTP",
        QTYRES: 0,
        QTYMFL: 0,
        QTYCOM: 0,
        HASBYPASS: " ",
        BYPASSVALV: 0,
        BYPASSFITT: " ",
        HURRICANEP: " ",
        FAX: " ",
        WWTP: "No",
        ParentID: " ",
      },
    },
    {
      type: "Feature",
      id: 31,
      geometry: {
        type: "Point",
        coordinates: [-80.196494130961753, 26.045221734212952],
      },
      properties: {
        FID: 31,
        OBJECTID: 244,
        FACILITYID: "SB-01",
        STATIONID: "\u003cNull\u003e",
        BUILDYR: " ",
        STATIONTYP: " ",
        OWNEDBY: -14,
        LIFECYCLE: "Active",
        PROJECTNO: " ",
        WWSIZE: " ",
        LEVELRIM29: 0,
        LEVELINV29: 0,
        LEVELHIGH2: 0,
        LEVELLAG29: 0,
        LEVELLEAD2: 0,
        LEVELOFF29: 0,
        LEVELLOW29: 0,
        LEVELBASE2: 0,
        LEVELRIM88: 0,
        LEVELINV88: 0,
        LEVELHIGH8: 0,
        LEVELLAG88: 0,
        LEVELLEAD8: 0,
        LEVELOFF88: 0,
        LEVELLOW88: 0,
        LEVELBASE8: 0,
        MAINTBY: -7,
        GENERATOR: " ",
        FPLMETER: " ",
        FPLACCOUNT: " ",
        NUMBERPUMP: 0,
        LOCDESC: " ",
        GPSDATE: null,
        LATITUDE: "26.045221734213",
        LONGITUDE: "-80.1964941309618",
        COMMENTS: " ",
        LASTUPDATE: 1404950400000,
        LASTEDITOR: "HOLLYWOOD\\mzaske",
        INSTALLYR: " ",
        COMPANY: "BC School Board - Hollywood Hills High",
        OWNERCONTA: "Set Aidie, P.E.",
        PHONEPAGER: " ",
        OFFICECELL: " ",
        OWNEREMAIL: " ",
        LIFTSTATIO: " ",
        STREETADDR: "5400 Stirling Rd",
        CITY: "Hollywood",
        STATE: "FL",
        ZIPCODE: "33021",
        MAILINGADD: " ",
        MAILINGCIT: " ",
        MAILINGSTA: " ",
        MAILINGZIP: " ",
        SPILLPLANA: " ",
        MAINTENANC: " ",
        MAINTENA_1: " ",
        MAINTENA_2: " ",
        MAINTENA_3: " ",
        STATIONVOL: " ",
        TITLE: " ",
        LASTNAME: " ",
        FIRSTNAME: " ",
        POSITION: " ",
        LSTYPE: " ",
        GOESTO: " ",
        QTYRES: 0,
        QTYMFL: 0,
        QTYCOM: 0,
        HASBYPASS: " ",
        BYPASSVALV: 0,
        BYPASSFITT: " ",
        HURRICANEP: " ",
        FAX: " ",
        WWTP: "No",
        ParentID: " ",
      },
    },
    {
      type: "Feature",
      id: 32,
      geometry: {
        type: "Point",
        coordinates: [-80.153085646269957, 26.016501448817827],
      },
      properties: {
        FID: 32,
        OBJECTID: 249,
        FACILITYID: "X-140",
        STATIONID: " ",
        BUILDYR: "2012",
        STATIONTYP: " ",
        OWNEDBY: -14,
        LIFECYCLE: "Active",
        PROJECTNO: " ",
        WWSIZE: " ",
        LEVELRIM29: 0,
        LEVELINV29: 0,
        LEVELHIGH2: 0,
        LEVELLAG29: 0,
        LEVELLEAD2: 0,
        LEVELOFF29: 0,
        LEVELLOW29: 0,
        LEVELBASE2: 0,
        LEVELRIM88: 0,
        LEVELINV88: 0,
        LEVELHIGH8: 0,
        LEVELLAG88: 0,
        LEVELLEAD8: 0,
        LEVELOFF88: 0,
        LEVELLOW88: 0,
        LEVELBASE8: 0,
        MAINTBY: -7,
        GENERATOR: " ",
        FPLMETER: " ",
        FPLACCOUNT: " ",
        NUMBERPUMP: 0,
        LOCDESC: " ",
        GPSDATE: null,
        LATITUDE: "26.0165014488178",
        LONGITUDE: "-80.15308564627",
        COMMENTS: " ",
        LASTUPDATE: 1578960000000,
        LASTEDITOR: "HOLLYWOOD\\mzaske",
        INSTALLYR: " ",
        COMPANY: "BC School Board",
        OWNERCONTA: " ",
        PHONEPAGER: " ",
        OFFICECELL: " ",
        OWNEREMAIL: " ",
        LIFTSTATIO: " ",
        STREETADDR: "2240 Lincoln St",
        CITY: "Hollywood",
        STATE: "FL",
        ZIPCODE: "33020",
        MAILINGADD: " ",
        MAILINGCIT: " ",
        MAILINGSTA: " ",
        MAILINGZIP: " ",
        SPILLPLANA: " ",
        MAINTENANC: " ",
        MAINTENA_1: " ",
        MAINTENA_2: " ",
        MAINTENA_3: " ",
        STATIONVOL: " ",
        TITLE: " ",
        LASTNAME: " ",
        FIRSTNAME: " ",
        POSITION: " ",
        LSTYPE: " ",
        GOESTO: " ",
        QTYRES: 0,
        QTYMFL: 0,
        QTYCOM: 0,
        HASBYPASS: " ",
        BYPASSVALV: 0,
        BYPASSFITT: " ",
        HURRICANEP: " ",
        FAX: " ",
        WWTP: "No",
        ParentID: " ",
      },
    },
    {
      type: "Feature",
      id: 33,
      geometry: {
        type: "Point",
        coordinates: [-80.111775944950352, 26.06588682909895],
      },
      properties: {
        FID: 33,
        OBJECTID: 254,
        FACILITYID: "FL-01",
        STATIONID: "E123-01",
        BUILDYR: " ",
        STATIONTYP: " ",
        OWNEDBY: -8,
        LIFECYCLE: "Active",
        PROJECTNO: " ",
        WWSIZE: " ",
        LEVELRIM29: 0,
        LEVELINV29: 0,
        LEVELHIGH2: 0,
        LEVELLAG29: 0,
        LEVELLEAD2: 0,
        LEVELOFF29: 0,
        LEVELLOW29: 0,
        LEVELBASE2: 0,
        LEVELRIM88: 0,
        LEVELINV88: 0,
        LEVELHIGH8: 0,
        LEVELLAG88: 0,
        LEVELLEAD8: 0,
        LEVELOFF88: 0,
        LEVELLOW88: 0,
        LEVELBASE8: 0,
        MAINTBY: -5,
        GENERATOR: " ",
        FPLMETER: " ",
        FPLACCOUNT: " ",
        NUMBERPUMP: 0,
        LOCDESC: " ",
        GPSDATE: 1133395200000,
        LATITUDE: "26.065886829099",
        LONGITUDE: "-80.1117759449504",
        COMMENTS: " ",
        LASTUPDATE: 1404950400000,
        LASTEDITOR: "HOLLYWOOD\\mzaske",
        INSTALLYR: " ",
        COMPANY: "FL Dept. of Environmental Protection",
        OWNERCONTA: "Mr. Sidney J. Leve",
        PHONEPAGER: "954-924-3859",
        OFFICECELL: " ",
        OWNEREMAIL: " ",
        LIFTSTATIO: " ",
        STREETADDR: "6503 N Ocean Dr",
        CITY: "Hollywood",
        STATE: "FL",
        ZIPCODE: "33004",
        MAILINGADD: "6503 N Ocean Dr",
        MAILINGCIT: "Dania Beach",
        MAILINGSTA: "FL",
        MAILINGZIP: "33004",
        SPILLPLANA: " ",
        MAINTENANC: " ",
        MAINTENA_1: " ",
        MAINTENA_2: " ",
        MAINTENA_3: " ",
        STATIONVOL: " ",
        TITLE: " ",
        LASTNAME: " ",
        FIRSTNAME: " ",
        POSITION: " ",
        LSTYPE: " ",
        GOESTO: " ",
        QTYRES: 0,
        QTYMFL: 0,
        QTYCOM: 0,
        HASBYPASS: " ",
        BYPASSVALV: 0,
        BYPASSFITT: " ",
        HURRICANEP: " ",
        FAX: " ",
        WWTP: "No",
        ParentID: " ",
      },
    },
    {
      type: "Feature",
      id: 34,
      geometry: {
        type: "Point",
        coordinates: [-80.110270065869244, 26.083265157716397],
      },
      properties: {
        FID: 34,
        OBJECTID: 255,
        FACILITYID: "FL-04",
        STATIONID: "E123-03",
        BUILDYR: " ",
        STATIONTYP: " ",
        OWNEDBY: -8,
        LIFECYCLE: "Active",
        PROJECTNO: " ",
        WWSIZE: " ",
        LEVELRIM29: 0,
        LEVELINV29: 0,
        LEVELHIGH2: 0,
        LEVELLAG29: 0,
        LEVELLEAD2: 0,
        LEVELOFF29: 0,
        LEVELLOW29: 0,
        LEVELBASE2: 0,
        LEVELRIM88: 0,
        LEVELINV88: 0,
        LEVELHIGH8: 0,
        LEVELLAG88: 0,
        LEVELLEAD8: 0,
        LEVELOFF88: 0,
        LEVELLOW88: 0,
        LEVELBASE8: 0,
        MAINTBY: -5,
        GENERATOR: " ",
        FPLMETER: " ",
        FPLACCOUNT: " ",
        NUMBERPUMP: 0,
        LOCDESC: " ",
        GPSDATE: 1133395200000,
        LATITUDE: "26.0832651577164",
        LONGITUDE: "-80.1102700658692",
        COMMENTS: " ",
        LASTUPDATE: 1404950400000,
        LASTEDITOR: "HOLLYWOOD\\mzaske",
        INSTALLYR: " ",
        COMPANY: "FL Dept. of Environmental Protection",
        OWNERCONTA: "Mr. Sidney J. Leve",
        PHONEPAGER: "954-924-3859",
        OFFICECELL: " ",
        OWNEREMAIL: " ",
        LIFTSTATIO: " ",
        STREETADDR: "6503 N Ocean Dr",
        CITY: "Hollywood",
        STATE: "FL",
        ZIPCODE: "33004",
        MAILINGADD: "6503 N Ocean Dr",
        MAILINGCIT: "Dania Beach",
        MAILINGSTA: "FL",
        MAILINGZIP: "33004",
        SPILLPLANA: " ",
        MAINTENANC: " ",
        MAINTENA_1: " ",
        MAINTENA_2: " ",
        MAINTENA_3: " ",
        STATIONVOL: " ",
        TITLE: " ",
        LASTNAME: " ",
        FIRSTNAME: " ",
        POSITION: " ",
        LSTYPE: " ",
        GOESTO: " ",
        QTYRES: 0,
        QTYMFL: 0,
        QTYCOM: 0,
        HASBYPASS: " ",
        BYPASSVALV: 0,
        BYPASSFITT: " ",
        HURRICANEP: " ",
        FAX: " ",
        WWTP: "No",
        ParentID: " ",
      },
    },
    {
      type: "Feature",
      id: 35,
      geometry: {
        type: "Point",
        coordinates: [-80.109831451064196, 26.088259335387882],
      },
      properties: {
        FID: 35,
        OBJECTID: 256,
        FACILITYID: "FL-02",
        STATIONID: "E123-02",
        BUILDYR: " ",
        STATIONTYP: " ",
        OWNEDBY: -8,
        LIFECYCLE: "Active",
        PROJECTNO: " ",
        WWSIZE: " ",
        LEVELRIM29: 0,
        LEVELINV29: 0,
        LEVELHIGH2: 0,
        LEVELLAG29: 0,
        LEVELLEAD2: 0,
        LEVELOFF29: 0,
        LEVELLOW29: 0,
        LEVELBASE2: 0,
        LEVELRIM88: 0,
        LEVELINV88: 0,
        LEVELHIGH8: 0,
        LEVELLAG88: 0,
        LEVELLEAD8: 0,
        LEVELOFF88: 0,
        LEVELLOW88: 0,
        LEVELBASE8: 0,
        MAINTBY: -5,
        GENERATOR: " ",
        FPLMETER: " ",
        FPLACCOUNT: " ",
        NUMBERPUMP: 0,
        LOCDESC: " ",
        GPSDATE: 1133395200000,
        LATITUDE: "26.0882593353879",
        LONGITUDE: "-80.1098314510642",
        COMMENTS: " ",
        LASTUPDATE: 1404950400000,
        LASTEDITOR: "HOLLYWOOD\\mzaske",
        INSTALLYR: " ",
        COMPANY: "FL Dept. of Environmental Protection",
        OWNERCONTA: "Mr. Sidney J. Leve",
        PHONEPAGER: "954-924-3859",
        OFFICECELL: " ",
        OWNEREMAIL: " ",
        LIFTSTATIO: " ",
        STREETADDR: "6503 N Ocean Dr",
        CITY: "Hollywood",
        STATE: "FL",
        ZIPCODE: "33004",
        MAILINGADD: "6503 N Ocean Dr",
        MAILINGCIT: "Dania Beach",
        MAILINGSTA: "FL",
        MAILINGZIP: "33004",
        SPILLPLANA: " ",
        MAINTENANC: " ",
        MAINTENA_1: " ",
        MAINTENA_2: " ",
        MAINTENA_3: " ",
        STATIONVOL: " ",
        TITLE: " ",
        LASTNAME: " ",
        FIRSTNAME: " ",
        POSITION: " ",
        LSTYPE: " ",
        GOESTO: " ",
        QTYRES: 0,
        QTYMFL: 0,
        QTYCOM: 0,
        HASBYPASS: " ",
        BYPASSVALV: 0,
        BYPASSFITT: " ",
        HURRICANEP: " ",
        FAX: " ",
        WWTP: "No",
        ParentID: " ",
      },
    },
    {
      type: "Feature",
      id: 36,
      geometry: {
        type: "Point",
        coordinates: [-80.192110097650698, 26.050018455000423],
      },
      properties: {
        FID: 36,
        OBJECTID: 6681,
        FACILITYID: "X-155",
        STATIONID: " ",
        BUILDYR: "2016",
        STATIONTYP: "Submersible",
        OWNEDBY: -3,
        LIFECYCLE: "Active",
        PROJECTNO: "14-1072",
        WWSIZE: "8",
        LEVELRIM29: 0,
        LEVELINV29: 0,
        LEVELHIGH2: 0,
        LEVELLAG29: 0,
        LEVELLEAD2: 0,
        LEVELOFF29: 0,
        LEVELLOW29: 0,
        LEVELBASE2: 0,
        LEVELRIM88: 0,
        LEVELINV88: 0,
        LEVELHIGH8: 0,
        LEVELLAG88: 0,
        LEVELLEAD8: 0,
        LEVELOFF88: 0,
        LEVELLOW88: 0,
        LEVELBASE8: 0,
        MAINTBY: -6,
        GENERATOR: " ",
        FPLMETER: " ",
        FPLACCOUNT: " ",
        NUMBERPUMP: 2,
        LOCDESC: " ",
        GPSDATE: null,
        LATITUDE: "26.0500184550004",
        LONGITUDE: "-80.1921100976507",
        COMMENTS: "Private LS in BC Service Area.",
        LASTUPDATE: 1547683200000,
        LASTEDITOR: "HOLLYWOOD\\mzaske",
        INSTALLYR: "2016",
        COMPANY: " ",
        OWNERCONTA: " ",
        PHONEPAGER: " ",
        OFFICECELL: " ",
        OWNEREMAIL: " ",
        LIFTSTATIO: " ",
        STREETADDR: " ",
        CITY: " ",
        STATE: " ",
        ZIPCODE: " ",
        MAILINGADD: " ",
        MAILINGCIT: " ",
        MAILINGSTA: " ",
        MAILINGZIP: " ",
        SPILLPLANA: " ",
        MAINTENANC: " ",
        MAINTENA_1: " ",
        MAINTENA_2: " ",
        MAINTENA_3: " ",
        STATIONVOL: " ",
        TITLE: " ",
        LASTNAME: " ",
        FIRSTNAME: " ",
        POSITION: " ",
        LSTYPE: "Residential",
        GOESTO: "Broward County",
        QTYRES: 0,
        QTYMFL: 0,
        QTYCOM: 0,
        HASBYPASS: " ",
        BYPASSVALV: 0,
        BYPASSFITT: " ",
        HURRICANEP: " ",
        FAX: " ",
        WWTP: "No",
        ParentID: " ",
      },
    },
    {
      type: "Feature",
      id: 37,
      geometry: {
        type: "Point",
        coordinates: [-80.16859743787407, 26.036505880938638],
      },
      properties: {
        FID: 37,
        OBJECTID: 7883,
        FACILITYID: "BC-05",
        STATIONID: "NW107-04",
        BUILDYR: "2007",
        STATIONTYP: "Submersible",
        OWNEDBY: -3,
        LIFECYCLE: "Active",
        PROJECTNO: " ",
        WWSIZE: " ",
        LEVELRIM29: 0,
        LEVELINV29: 0,
        LEVELHIGH2: 0,
        LEVELLAG29: 0,
        LEVELLEAD2: 0,
        LEVELOFF29: 0,
        LEVELLOW29: 0,
        LEVELBASE2: 0,
        LEVELRIM88: 0,
        LEVELINV88: 0,
        LEVELHIGH8: 0,
        LEVELLAG88: 0,
        LEVELLEAD8: 0,
        LEVELOFF88: 0,
        LEVELLOW88: 0,
        LEVELBASE8: 0,
        MAINTBY: -6,
        GENERATOR: "No",
        FPLMETER: " ",
        FPLACCOUNT: " ",
        NUMBERPUMP: 2,
        LOCDESC: "RV Entrance in TY park",
        GPSDATE: null,
        LATITUDE: "26.0365058809386",
        LONGITUDE: "-80.1685974378741",
        COMMENTS: " ",
        LASTUPDATE: 1602547200000,
        LASTEDITOR: "HOLLYWOOD\\JDIAZ-MARIN",
        INSTALLYR: "2007",
        COMPANY: "Broward County Parks and Recreation",
        OWNERCONTA: "Mr. Robert Sangiugni",
        PHONEPAGER: "Bob 954-410-4741 /  Fred 954-296-7433",
        OFFICECELL: "954-357-8753",
        OWNEREMAIL: "rsanguigni@broward.org",
        LIFTSTATIO: "RV Entrance in TY park",
        STREETADDR: "3300 Park Road",
        CITY: "Hollywood",
        STATE: "FL",
        ZIPCODE: "33021",
        MAILINGADD: "3900 SW 100th Ave.",
        MAILINGCIT: "Davie",
        MAILINGSTA: "FL",
        MAILINGZIP: "33328",
        SPILLPLANA: " ",
        MAINTENANC: "Broward Co. Staff- Brian Ortegus",
        MAINTENA_1: "Internal Maintenance",
        MAINTENA_2: "954-357-8753 (office)/Bob 954-410-4741 (cell)",
        MAINTENA_3: "fpulver@broward.org",
        STATIONVOL: "230",
        TITLE: "Mr.",
        LASTNAME: "Sangiugni",
        FIRSTNAME: "Robert",
        POSITION: "Maintenance Supervisor",
        LSTYPE: "Residential",
        GOESTO: "SRWWTP",
        QTYRES: 64,
        QTYMFL: 0,
        QTYCOM: 0,
        HASBYPASS: "Yes",
        BYPASSVALV: 4,
        BYPASSFITT: "Camlock",
        HURRICANEP: "Close Facility",
        FAX: " ",
        WWTP: "No",
        ParentID: " ",
      },
    },
    {
      type: "Feature",
      id: 38,
      geometry: {
        type: "Point",
        coordinates: [-80.206812889384167, 26.063150979692125],
      },
      properties: {
        FID: 38,
        OBJECTID: 9083,
        FACILITYID: " ",
        STATIONID: " ",
        BUILDYR: "2019",
        STATIONTYP: "Submersible",
        OWNEDBY: -3,
        LIFECYCLE: "Active",
        PROJECTNO: "18-2017",
        WWSIZE: "8",
        LEVELRIM29: 0,
        LEVELINV29: 0,
        LEVELHIGH2: 0,
        LEVELLAG29: 0,
        LEVELLEAD2: 0,
        LEVELOFF29: 0,
        LEVELLOW29: 0,
        LEVELBASE2: 0,
        LEVELRIM88: 7.2000000000000002,
        LEVELINV88: -1.5,
        LEVELHIGH8: -4.7599999999999998,
        LEVELLAG88: -5.7599999999999998,
        LEVELLEAD8: -6.7599999999999998,
        LEVELOFF88: -8.7599999999999998,
        LEVELLOW88: -9.2599999999999998,
        LEVELBASE8: -11,
        MAINTBY: -6,
        GENERATOR: " ",
        FPLMETER: " ",
        FPLACCOUNT: " ",
        NUMBERPUMP: 2,
        LOCDESC: "2572 Griffin Rd",
        GPSDATE: null,
        LATITUDE: "26.0631509796921",
        LONGITUDE: "-80.2068128893842",
        COMMENTS: " ",
        LASTUPDATE: 1573171200000,
        LASTEDITOR: "HOLLYWOOD\\mzaske",
        INSTALLYR: "2019",
        COMPANY: " ",
        OWNERCONTA: " ",
        PHONEPAGER: " ",
        OFFICECELL: " ",
        OWNEREMAIL: " ",
        LIFTSTATIO: " ",
        STREETADDR: " ",
        CITY: " ",
        STATE: " ",
        ZIPCODE: " ",
        MAILINGADD: " ",
        MAILINGCIT: " ",
        MAILINGSTA: " ",
        MAILINGZIP: " ",
        SPILLPLANA: " ",
        MAINTENANC: " ",
        MAINTENA_1: " ",
        MAINTENA_2: " ",
        MAINTENA_3: " ",
        STATIONVOL: " ",
        TITLE: " ",
        LASTNAME: " ",
        FIRSTNAME: " ",
        POSITION: " ",
        LSTYPE: " ",
        GOESTO: "Broward County",
        QTYRES: 0,
        QTYMFL: 0,
        QTYCOM: 0,
        HASBYPASS: "Yes",
        BYPASSVALV: 4,
        BYPASSFITT: "Flanged KamLock",
        HURRICANEP: " ",
        FAX: " ",
        WWTP: "No",
        ParentID: " ",
      },
    },
    {
      type: "Feature",
      id: 39,
      geometry: {
        type: "Point",
        coordinates: [-80.17875417797913, 26.025468533712157],
      },
      properties: {
        FID: 39,
        OBJECTID: 9484,
        FACILITYID: " ",
        STATIONID: " ",
        BUILDYR: "2005",
        STATIONTYP: "Submersible",
        OWNEDBY: -14,
        LIFECYCLE: "Active",
        PROJECTNO: "03-2099",
        WWSIZE: " ",
        LEVELRIM29: 0,
        LEVELINV29: 0,
        LEVELHIGH2: 0,
        LEVELLAG29: 0,
        LEVELLEAD2: 0,
        LEVELOFF29: 0,
        LEVELLOW29: 0,
        LEVELBASE2: 0,
        LEVELRIM88: 0,
        LEVELINV88: 0,
        LEVELHIGH8: 0,
        LEVELLAG88: 0,
        LEVELLEAD8: 0,
        LEVELOFF88: 0,
        LEVELLOW88: 0,
        LEVELBASE8: 0,
        MAINTBY: -7,
        GENERATOR: " ",
        FPLMETER: " ",
        FPLACCOUNT: " ",
        NUMBERPUMP: 2,
        LOCDESC: " ",
        GPSDATE: null,
        LATITUDE: "26.0254685337122",
        LONGITUDE: "-80.1787541779791",
        COMMENTS: " ",
        LASTUPDATE: 1583193600000,
        LASTEDITOR: "HOLLYWOOD\\mzaske",
        INSTALLYR: "2005",
        COMPANY: " ",
        OWNERCONTA: " ",
        PHONEPAGER: " ",
        OFFICECELL: " ",
        OWNEREMAIL: " ",
        LIFTSTATIO: " ",
        STREETADDR: " ",
        CITY: " ",
        STATE: " ",
        ZIPCODE: " ",
        MAILINGADD: " ",
        MAILINGCIT: " ",
        MAILINGSTA: " ",
        MAILINGZIP: " ",
        SPILLPLANA: " ",
        MAINTENANC: " ",
        MAINTENA_1: " ",
        MAINTENA_2: " ",
        MAINTENA_3: " ",
        STATIONVOL: " ",
        TITLE: " ",
        LASTNAME: " ",
        FIRSTNAME: " ",
        POSITION: " ",
        LSTYPE: " ",
        GOESTO: "SRWWTP",
        QTYRES: 0,
        QTYMFL: 0,
        QTYCOM: 1,
        HASBYPASS: " ",
        BYPASSVALV: 0,
        BYPASSFITT: " ",
        HURRICANEP: " ",
        FAX: " ",
        WWTP: "No",
        ParentID: " ",
      },
    },
  ],
};
